/* log-agent-run.cjs: the company modes, the --start/finish extensions, the
 * dashboard inbox, closing gates, and proof that existing run logs are never
 * rewritten. Each test runs the real CLI in a throwaway data folder. */
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')
const { makeSandbox, hashTree } = require('./helpers.cjs')

function initialised(t) {
  const sb = makeSandbox()
  t.after(() => sb.cleanup())
  const r = sb.cli('--company-init', '--seed', sb.seed())
  assert.equal(r.code, 0, r.err)
  return sb
}

test('--company-init creates the folder once; a second run refuses', (t) => {
  const sb = initialised(t)
  assert.ok(fs.existsSync(path.join(sb.company, 'company.json')))
  const emp = sb.read('company/employees.json')
  assert.deepEqual(Object.keys(emp).sort(), ['code-reviewer', 'engineering-lead', 'implementer', 'product-lead', 'tester', 'ui-designer'])
  assert.equal(emp['engineering-lead'].zone, 'lead')
  assert.equal(emp.tester.reportsTo, 'engineering-lead')
  const again = sb.cli('--company-init')
  assert.equal(again.code, 1)
  assert.match(again.err, /already exists/)
})

test('AT-10: --budget-check exits 2 on stop; --start still records the run, flagged, with a WARNING', (t) => {
  const sb = initialised(t)
  sb.measured('tester', 'democalc', 505000)
  assert.equal(sb.cli('--budget', '{"scope":"employee","id":"tester","budget":{"monthlyTokens":500000,"hardStop":true},"by":"board"}').code, 0)
  const chk = sb.cli('--budget-check', '{"agent":"tester"}')
  assert.equal(chk.code, 2)
  assert.match(chk.out, /^stop employee:tester 505000\/500000$/m)
  const st = sb.cli('--start', '{"agent":"tester","model":"sonnet","task":"invented task","project":"democalc","session":"main","issue":"DCALC-1"}')
  assert.equal(st.code, 0)
  assert.match(st.err, /^WARNING: budget stop/)
  const active = sb.read('agent-runs/active/' + st.out + '.json')
  assert.equal(active.budgetWarned, true)
  assert.equal(active.budgetLevel, 'stop')
  assert.equal(active.session, 'main')
  assert.equal(active.issue, 'DCALC-1')
  assert.ok(sb.lines('company/activity.jsonl').some((l) => l.action === 'budget.violation' && l.entityId === 'tester'))
  // finishing keeps the company fields and the flag in the run record
  const fin = sb.cli('{"id":"' + st.out + '","agent":"tester","task":"invented task","status":"ok","usage":{"tokens":1000}}')
  assert.equal(fin.code, 0, fin.err)
  const rec = JSON.parse(fs.readFileSync(path.join(sb.base, fin.out), 'utf8'))
  assert.equal(rec.budgetLevel, 'stop')
  assert.equal(rec.session, 'main')
  assert.equal(rec.issue, 'DCALC-1')
})

test('budgets off: no refusal, no warning; on again: the stop is back', (t) => {
  const sb = initialised(t)
  sb.measured('tester', 'democalc', 505000)
  sb.cli('--budget', '{"scope":"office","id":"engineering","budget":{"monthlyTokens":500000,"hardStop":true},"by":"board"}')
  assert.equal(sb.cli('--budget-check', '{"agent":"tester","project":"democalc"}').code, 2)
  const off = sb.cli('--budgets', 'off', '{"by":"board"}')
  assert.equal(off.code, 0)
  assert.equal(sb.read('company/company.json').budgetsEnabled, false)
  const chk = sb.cli('--budget-check', '{"agent":"tester","project":"democalc"}')
  assert.equal(chk.code, 0)
  assert.match(chk.out, /^ok/)
  const st = sb.cli('--start', '{"agent":"tester","task":"invented task","project":"democalc"}')
  assert.equal(st.err, '')
  assert.equal(sb.read('agent-runs/active/' + st.out + '.json').budgetWarned, undefined)
  sb.cli('--budgets', 'on', '{"by":"board"}')
  assert.equal(sb.cli('--budget-check', '{"agent":"tester","project":"democalc"}').code, 2)
  assert.equal(sb.cli('--budgets', 'off').code, 1, 'the switch is the owner\'s: "by":"board" is required')
})

test('--budget refuses bad numbers and a missing "by":"board"; nothing is written', (t) => {
  const sb = initialised(t)
  const before = hashTree(sb.company)
  let r = sb.cli('--budget', '{"scope":"employee","id":"tester","budget":{"monthlyTokens":"1M"},"by":"board"}')
  assert.equal(r.code, 1)
  assert.match(r.err, /Enter a whole number of tokens, for example 2000000/)
  r = sb.cli('--budget', '{"scope":"employee","id":"tester","budget":{"monthlyTokens":5}}')
  assert.equal(r.code, 1)
  assert.match(r.err, /only the Board/)
  r = sb.cli('--budget', '{"scope":"office","id":"nope","budget":{"monthlyTokens":5},"by":"board"}')
  assert.equal(r.code, 1)
  assert.deepEqual(hashTree(sb.company), before)
})

test('--employee: the cycle guard and the pause', (t) => {
  const sb = initialised(t)
  assert.equal(sb.cli('--employee', '{"id":"code-reviewer","reportsTo":"implementer","by":"board"}').code, 0)
  const r = sb.cli('--employee', '{"id":"implementer","reportsTo":"code-reviewer","by":"board"}')
  assert.equal(r.code, 1)
  assert.match(r.err, /would create a cycle: implementer → code-reviewer → implementer/)
  assert.equal(sb.cli('--employee', '{"id":"tester","status":"paused","pauseReason":"owner asked","by":"board"}').code, 0)
  const chk = sb.cli('--budget-check', '{"agent":"tester"}')
  assert.equal(chk.code, 2)
  assert.match(chk.out, /stop employee:tester paused \(owner asked\)/)
})

test('AT-8 through the CLI: finishing the run that crosses 80 % logs one incident', (t) => {
  const sb = initialised(t)
  sb.cli('--budget', '{"scope":"employee","id":"implementer","budget":{"monthlyTokens":1000000},"by":"board"}')
  sb.measured('implementer', 'democalc', 790000)
  const st = sb.cli('--start', '{"agent":"implementer","task":"invented task","project":"democalc"}')
  // a transcript the finish counts: one assistant message with 20,000 new
  // tokens, inside a configured transcript root (anything else is refused)
  fs.mkdirSync(path.join(sb.base, 'transcripts'))
  fs.writeFileSync(path.join(sb.root, 'config.json'), JSON.stringify({ transcriptRoots: [path.join(sb.base, 'transcripts')] }))
  const tr = path.join(sb.base, 'transcripts', 'tr.jsonl')
  fs.writeFileSync(tr,JSON.stringify({ type: 'assistant', message: { id: 'm1', model: 'claude-sonnet-5-5', usage: { input_tokens: 20000, output_tokens: 0 }, content: [] } }) + '\n')
  const fin = sb.cli(JSON.stringify({ id: st.out, agent: 'implementer', task: 'invented task', project: 'democalc', transcript: tr }))
  assert.match(fin.err, /WARNING: budget alert — employee implementer at 81%/)
  assert.equal(sb.lines('company/budget-incidents.jsonl').filter((l) => l.scope === 'employee').length, 1)
  sb.measured('implementer', 'democalc', 5000)
  const st2 = sb.cli('--start', '{"agent":"implementer","task":"invented task 2","project":"democalc"}')
  const fin2 = sb.cli(JSON.stringify({ id: st2.out, agent: 'implementer', task: 'invented task 2', project: 'democalc' }))
  assert.doesNotMatch(fin2.err, /budget alert/)
  assert.equal(sb.lines('company/budget-incidents.jsonl').filter((l) => l.scope === 'employee').length, 1)
})

test('--inbox prints the Board\'s dashboard changes once, then "No new items"', (t) => {
  const sb = initialised(t)
  const C = sb.mod('agent-company.cjs')
  C.setBudget({ scope: 'office', id: 'studio', budget: { monthlyTokens: 3000000 }, by: 'board' }, 'dashboard')
  C.setBudgetsEnabled(false, 'board', 'dashboard')
  // a CLI change is the supervisor's own: it is not an inbox item
  C.setBudget({ scope: 'office', id: 'hq', budget: { monthlyTokens: 1 }, by: 'board' }, 'cli')
  assert.match(sb.cli('--inbox', '--peek').out, /^2 new items:/)
  const r = sb.cli('--inbox')
  assert.match(r.out, /2 new items \(now marked read\)/)
  assert.match(r.out, /office studio budget: 3000000 tokens\/month/)
  assert.match(r.out, /budgets switched off company-wide/)
  assert.equal(sb.cli('--inbox').out, 'No new items.')
  assert.equal(JSON.parse(sb.cli('--inbox', '--all', '--json').out).length, 2)
})

test('--heartbeat and --answers stamp the supervisor; without a company nothing is created', (t) => {
  const bare = makeSandbox()
  t.after(() => bare.cleanup())
  assert.match(bare.cli('--heartbeat').out, /no company configured/)
  assert.equal(bare.cli('--answers').out, 'No new answers.')
  assert.equal(fs.existsSync(bare.company), false)
  const sb = initialised(t)
  assert.equal(sb.cli('--heartbeat', '{"session":"main"}').out, 'ok')
  assert.equal(sb.read('company/heartbeat.json').supervisor.session, 'main')
  fs.unlinkSync(path.join(sb.company, 'heartbeat.json'))
  sb.cli('--answers')
  assert.ok(sb.read('company/heartbeat.json').supervisor.lastSeenAt)
})

test('--dismiss closes waiting gates; --dismiss-older-than picks only old ones; --dry-run changes nothing', (t) => {
  const sb = makeSandbox()
  t.after(() => sb.cleanup())
  const g1 = sb.cli('--gate', '{"project":"demo","kind":"C","question":"invented question one?"}').out
  const g2 = sb.cli('--gate', '{"project":"demo","kind":"A","question":"invented question two?"}').out
  // make the first one two days old
  const f1 = path.join(sb.runs, 'gates', g1 + '.json')
  const old = JSON.parse(fs.readFileSync(f1, 'utf8'))
  old.askedAt = new Date(Date.now() - 48 * 3600000).toISOString()
  fs.writeFileSync(f1, JSON.stringify(old))
  const dry = sb.cli('--dismiss-older-than', '24h', '--dry-run')
  assert.match(dry.out, new RegExp('would dismiss ' + g1))
  assert.doesNotMatch(dry.out, new RegExp(g2))
  assert.equal(sb.read('agent-runs/gates/' + g1 + '.json').status, 'waiting')
  const r = sb.cli('--dismiss-older-than', '24h')
  assert.equal(r.code, 0)
  assert.equal(sb.read('agent-runs/gates/' + g1 + '.json').status, 'expired')
  assert.equal(sb.read('agent-runs/gates/' + g2 + '.json').status, 'waiting')
  assert.equal(sb.cli('--dismiss', g2).code, 0)
  assert.equal(sb.read('agent-runs/gates/' + g2 + '.json').status, 'expired')
  const again = sb.cli('--dismiss', g2)
  assert.equal(again.code, 1)
  assert.match(again.err, /is expired, left as it is/)
  assert.equal(sb.cli('--dismiss-older-than', 'soon').code, 1)
})

test('migration: a whole session of new CLI modes leaves every existing run log byte-identical', (t) => {
  const sb = makeSandbox()
  t.after(() => sb.cleanup())
  // records in the shapes older CLIs wrote: no id, no usage, no transcript, free-text projects
  sb.run({ project: 'democalc' })
  sb.run({ agent: 'crew-tester', project: 'Demo Calc (branch x)', tokens: 1234 })
  sb.measured('tester', 'tide', 500, { id: 'r-old-1', parent: '' })
  fs.writeFileSync(path.join(sb.runs, 'answers.jsonl'), JSON.stringify({ at: new Date().toISOString(), gate: 'g-x', question: 'q', answer: 'a' }) + '\n')
  const before = hashTree(sb.runs)
  sb.cli('--company-init', '--seed', sb.seed())
  sb.cli('--company-status')
  sb.cli('--budget', '{"scope":"company","budget":{"monthlyTokens":10},"by":"board"}')
  sb.cli('--budget-check', '{"agent":"tester"}')
  sb.cli('--inbox')
  sb.cli('--heartbeat')
  sb.cli('--answers', '--peek')
  const after = hashTree(sb.runs)
  for (const [f, h] of Object.entries(before)) assert.equal(after[f], h, f + ' changed')
  const status = sb.cli('--company-status')
  assert.match(status.out, /company: 1734 tokens, USD n\/a, 3 runs \(1 unmeasured\)/)
})
