/* UI strings for the agent dashboard, English and Persian.
 *
 * English is the source language: every render function — whether it runs in
 * Node (the office/archive HTML shell, produced once per request) or in the
 * browser (officeClient/controlRoom/SCRIPT, injected as source text and run
 * client-side) — calls T(key) with the *English* text already sitting in the
 * code, and T looks up FA[key] when the page is in Persian. There is no
 * separate `en` table: a key that is not in FA simply falls back to itself.
 *
 * This file is required directly by the two Node-side renderers
 * (agent-office-page.cjs, build-agent-dashboard.cjs) for the static shell
 * text. For the browser-side functions, FA is serialized into the page
 * (`const FA = ${JSON.stringify(FA)}`) and a small T(key) is defined inline
 * in the injected <script> — see renderOffice() and renderArchive().
 *
 * The Persian text below is recovered from the dashboard's original Persian
 * UI (git history before commit 0979ef2, "Make the agent dashboard English by
 * default"), not re-translated — keep it that way if English strings change:
 * update the Persian to match, don't guess a fresh translation from scratch.
 *
 * A few English strings are reused unchanged in Persian on purpose (agent
 * names, model names and ids, --flags): they simply have no FA entry.
 */
const FA = {
  // ---------- shared: status words, "who" labels, generic fragments
  'Working': 'در کار',
  'No issues': 'بدون ایراد',
  'Has findings': 'دارای ایراد',
  'Failed': 'ناموفق',
  'Stopped': 'متوقف‌شده',
  'Quiet': 'بی‌خبر',
  'You': 'شما',
  'Supervisor': 'سرپرست',
  'Agents': 'ایجنت‌ها',
  'Waiting for you': 'منتظر شما',
  'waiting for you': 'منتظر شما',
  'agent': 'ایجنت',
  'supervisor': 'سرپرست',
  'now': 'اکنون',
  'Now': 'اکنون',
  ', ': '، ',
  ' min': ' دقیقه',
  'unknown': 'نامشخص',
  'All projects': 'همهٔ پروژه‌ها',
  'not recorded': 'ثبت نشده',
  'No runs today.': 'امروز اجرایی نبوده.',
  'Model:': 'مدل:',
  'Agents defined': 'ایجنت‌های موجود',
  '● Live': '● زنده',
  'Live · every 1.5s': 'زنده · هر ۱٫۵ ثانیه',
  'Disconnected from server': 'بی‌ارتباط با سرور',
  'Updated at ': 'به‌روز شده در ',
  'Waiting for the first report from this agent…': 'در انتظار اولین گزارش این ایجنت…',
  'Waiting for the first report…': 'در انتظار اولین گزارش…',

  // ---------- control room: answer widgets, gates rail
  'Approve': 'تأیید',
  'Decline': 'رد',
  'Click again to send: ': 'برای ارسال دوباره بزنید: ',
  'Send “': 'ارسال «',
  '”?': '»؟',
  'Short answer…': 'پاسخ کوتاه…',
  'Answer to: ': 'پاسخ به: ',
  'Send': 'بفرست',
  'Show in the Decisions view': 'در نمای تصمیم‌ها نشان بده',
  'No gate logged today.': 'امروز دروازه‌ای ثبت نشده.',
  'No answer logged yet today.': 'امروز هنوز پاسخی ثبت نشده.',
  'Close ✕': 'بستن ✕',
  'Answer here, or reply to the supervisor in the chat. Oldest first.': 'همین‌جا پاسخ دهید یا در گفتگو به سرپرست. قدیمی‌ترین اول.',
  'Answer the supervisor in the chat. To answer from here, restart the dashboard server once.': 'پاسخ را در گفتگو به سرپرست بدهید. برای پاسخ از اینجا، سرور داشبورد را یک بار از نو اجرا کنید.',
  'Answer the supervisor in the chat. Answering from here only works while the page is open from the local server.': 'پاسخ را در گفتگو به سرپرست بدهید. پاسخ از اینجا فقط وقتی صفحه از سرور محلی باز است.',
  '” recorded. The supervisor picks it up from answers.jsonl.': '» ثبت شد. سرپرست آن را از answers.jsonl برمی‌دارد.',
  'Nothing is waiting for you.': 'چیزی منتظر شما نیست.',
  'Where did the tokens go? ': 'کجا توکن رفت؟ ',
  'summary for today': 'خلاصهٔ امروز',
  'Gates per project': 'دروازه‌ها در هر پروژه',
  'Your answers today': 'پاسخ‌های امروز شما',
  'Open the waiting-for-you rail, ': 'باز کردن ریل منتظر شما، ',
  ' items': ' مورد',
  'Open': 'باز',
  'self-decided': 'خودش گرفت',
  'answered': 'داده شد',
  'taken': 'گرفته شد',
  'Asked by ': 'پرسید ',
  ' · dashboard': ' · داشبورد',
  'expired': 'منقضی',
  'Decisions today': 'تصمیم‌های امروز',
  'All': 'همه',
  'Project': 'پروژه',
  'Nothing matches this filter.': 'با این فیلتر چیزی نیست.',
  'No decision or gate logged today. The supervisor logs them with <code dir="ltr">--decision</code> and <code dir="ltr">--gate</code>.':
    'امروز تصمیم یا دروازه‌ای ثبت نشده. سرپرست آن‌ها را با <code dir="ltr">--decision</code> و <code dir="ltr">--gate</code> ثبت می‌کند.',
  'Time': 'زمان',
  'Who': 'چه کسی',
  'Decision and reason': 'تصمیم و دلیل',
  'Run': 'اجرا',
  'Status': 'وضعیت',
  'Asked ': 'پرسش ',
  'Timeline of decisions today in three lanes: you, supervisor, agents': 'نوار زمانی تصمیم‌های امروز در سه ردیف: شما، سرپرست، ایجنت‌ها',

  // ---------- control room: tools & usage
  'No usage measured yet today.': 'امروز هنوز مصرفی اندازه‌گیری نشده.',
  ' heavy-model runs took ': ' اجرای مدل سنگین ‏',
  '%</b> of tokens and <b>': '%</b> توکن را برد و <b>',
  '%</b> of the time.': '%</b> زمان را.',
  'Largest single run: ': 'بزرگ‌ترین تک‌اجرا: ',
  'Enter each model price in ': 'قیمت هر مدل را در ',
  'set prices': 'قیمت‌ها را وارد کنید',
  ' no data': ' بی‌داده',
  'Tokens today': 'توکن امروز',
  'excludes cache reads': 'بی‌خواندن کش',
  'Heavy-model share': 'سهم مدل‌های سنگین',
  ' of ': ' از ',
  ' runs': ' اجرا',
  'Tool calls': 'فراخوانی ابزار',
  'Agent work time': 'زمان کار ایجنت‌ها',
  'hours': 'ساعت',
  'Cost (USD)': 'هزینه (دلار)',
  'No data': 'بدون داده',
  'runs without a transcript': 'اجرای بی‌رونوشت',
  'Tokens by agent': 'توکن بر اساس ایجنت',
  'from the transcript; input + cache writes + output': 'از رونوشت؛ ورودی + نوشتن کش + خروجی',
  'Heavy models': 'مدل‌های سنگین',
  'Other models': 'مدل‌های دیگر',
  '… = still running': '… = در حال اجرا',
  'no transcript': 'رونوشت ثبت نشده',
  ' — only the allowed tools are known': ' — فقط ابزارهای مجاز معلوم است',
  ' — not allowed in the definition': ' — در تعریف مجاز نیست',
  ' not allowed in the definition': ' در تعریف مجاز نیست',
  'not allowed in the definition': 'در تعریف مجاز نیست',
  ' — built-in agent, its allowed tools are not known here': ' — ایجنت داخلی، ابزارهای مجازش اینجا معلوم نیست',
  'Tools: allowed vs used': 'ابزار: مجاز در برابر استفاده',
  'number = calls today': 'عدد = فراخوانی امروز',
  'Other': 'دیگر',
  'used': 'استفاده شد',
  'allowed, 0 calls': 'مجاز، ۰ بار',
  ' open': ' باز',
  'no price': 'بی‌قیمت',
  'Runs today': 'اجراهای امروز',
  'newest first · files changed = Edit/Write in the transcript · ≈ = reported number, not counted':
    'جدیدترین اول · فایل تغییرکرده = Edit/Write در رونوشت · ≈ = عدد گزارش‌شده، نه شمرده',
  'End': 'پایان',
  'Agent': 'ایجنت',
  'Task': 'کار',
  'Model': 'مدل',
  'Duration': 'مدت',
  'Tokens': 'توکن',
  'Cost': 'هزینه',
  'Tools': 'ابزار',
  'Files changed': 'فایل تغییرکرده',
  'Decision': 'تصمیم',
  ' so far': ' تا الان',
  'Cache reads: ': 'خواندن از کش: ',
  'Files': 'فایل‌ها',
  ' changed, ': ' تغییر، ',
  ' read': ' خواندن',
  ' hidden': ' پنهان',
  'No file changed.': 'فایلی تغییر نکرد.',
  ' files read': ' فایل خوانده‌شده',
  ' confidential files (keys, licences, documents) were only counted, their names are not shown.':
    ' فایل محرمانه (کلید، مجوز، سند) فقط شمرده شد، نامش نشان داده نمی‌شود.',
  'The transcript file is no longer there.': 'فایل رونوشت دیگر آنجا نیست.',
  'This run transcript has not been found yet.': 'رونوشت این اجرا هنوز پیدا نشده.',
  'This run transcript was not recorded.': 'رونوشت این اجرا ثبت نشده.',
  'Tools and files: ': 'ابزارها و فایل‌ها: ',
  'Sending…': 'در حال ثبت…',
  'Not recorded: ': 'ثبت نشد: ',

  // ---------- office: departments, tags, bubbles
  'Build & release': 'ساخت و انتشار',
  'Review': 'بازبینی',
  'Docs': 'مستندات',
  'Design & spec': 'طراحی و شرح کار',
  'Supervisor desk': 'میز سرپرست',
  'Break room': 'استراحت',
  ', quiet': '، بی‌خبر',
  '◷ quiet for ': '◷ بی‌خبر ',
  ', ready. Last task: ': '، آماده. آخرین کار: ',
  ' reports handed in': ' گزارش تحویل شد',
  ' more': ' نفر دیگر',
  ' handed in a report: ': ' گزارش را تحویل داد: ',
  ' · delegated ': ' · واگذاری ',

  // ---------- office: inspector
  'No one has taken a task yet': 'هنوز کسی کاری نگرفته',
  'When the supervisor gives an agent a task, it sits down at its desk and you see its live log here.':
    'وقتی سرپرست کاری را به ایجنتی بدهد، او پشت میزش می‌نشیند و اینجا لاگ زنده‌اش را می‌بینید.',
  'Last report': 'آخرین گزارش',
  ' agents, 0 working': ' ایجنت، ۰ در کار',
  'The desks and break room are empty; no one who has not worked today has come to the office.':
    'میزها خالی‌اند و استراحتگاه هم؛ کسی که امروز کار نکرده به دفتر نیامده.',
  'Concurrent runs of this agent': 'کارهای هم‌زمان این ایجنت',
  'Run ': 'کار ',
  'Start': 'شروع',
  'Elapsed': 'گذشته',
  'Handed in': 'تحویل',
  ' min ago': ' دقیقه پیش',
  'agents had no work today:': 'ایجنت امروز کاری نداشته‌اند:',
  ' agents had no work today:': ' ایجنت امروز کاری نداشته‌اند:',
  'Under ': 'زیرِ ',
  'Delegated to ': 'سپرده به ',
  'Live log': 'لاگ زنده',
  'Log': 'لاگ',
  ' steps': ' قدم',
  'The step-by-step log for this run was not kept.': 'لاگ قدم‌به‌قدم این اجرا نگه داشته نشده است.',
  'Records from before this version did not keep <code dir="ltr">steps</code>.':
    'رکوردهای پیش از این نسخه <code dir="ltr">steps</code> را نگه نمی‌داشتند.',
  'Report': 'گزارش',
  'Not handed in yet — when it finishes, the agent puts the report slip on the supervisor desk.':
    'هنوز تحویل نشده — وقتی تمام شود، ایجنت برگهٔ گزارش را روی میز سرپرست می‌گذارد.',

  // ---------- office: drawer / shift board
  'Shift board': 'تابلوی شیفت امروز',
  'Handed in today': 'تحویل‌شده‌های امروز',
  'Back to the office ↓': 'بازگشت به دفتر ↓',
  'Shift board ↑': 'تابلوی شیفت امروز ↑',
  'Archive of every day': 'بایگانی همهٔ روزها',
  'Filter': 'فیلتر',
  'Has findings ': 'دارای ایراد ',
  'Failed ': 'ناموفق ',
  'Time flows right to left; each small line is one step, and hatching means more than ':
    'زمان از راست به چپ می‌رود؛ هر خط کوچک یک گام است و راه‌راه یعنی بیش از ',
  ' minutes of quiet.': ' دقیقه بی‌خبری.',
  'No report today with this result.': 'امروز گزارشی با این نتیجه نیست.',
  'No report handed in yet today.': 'امروز هنوز گزارشی تحویل نشده.',
  ' Last: ': ' آخرین: ',
  ' · new': ' · تازه',
  ' to ': ' تا ',
  'No work has started today yet. The first run logged opens a new lane here.':
    'امروز هنوز کاری شروع نشده. اولین اجرا که ثبت شود، اینجا یک خط تازه باز می‌شود.',
  'Reports land on this line · ': 'گزارش‌ها روی این خط فرود می‌آیند · ',

  // ---------- office: header, counts, legend, zoom
  'handed in': 'تحویل',
  ' pixels': ' پیکسل',
  '%': '٪',
  'Quiet for more than ': 'بی‌خبر بیش از ',

  // ---------- office: page shell (Node-rendered)
  'View': 'نما',
  'Office': 'دفتر',
  'Decisions & gates': 'تصمیم‌ها و دروازه‌ها',
  'Tools & usage': 'ابزار و مصرف',
  'Summary': 'خلاصه',
  'Built file · refreshes automatically': 'فایل ساخته‌شده · خودکار تازه می‌شود',
  'Agent details': 'جزئیات ایجنت',
  'Office view — mouse wheel or + and - to zoom, drag or arrow keys to pan, 0 to fit':
    'نمای دفتر — چرخ ماوس یا + و − برای زوم، کشیدن یا کلیدهای جهت برای جابه‌جایی، 0 برای نمای کامل',
  'Office zoom': 'بزرگ‌نمایی دفتر',
  'Zoom out (-)': 'کوچک‌نمایی (−)',
  'Zoom out': 'کوچک‌نمایی',
  'Zoom in (+)': 'بزرگ‌نمایی (+)',
  'Zoom in': 'بزرگ‌نمایی',
  'Fit whole office (0)': 'نمای کامل دفتر (0)',
  'Fit': 'کل دفتر',
  'Mouse wheel: zoom · Drag: pan': 'چرخ ماوس: زوم · کشیدن: جابه‌جایی',
  'Drag to resize the panel; double-click: default size': 'بکشید تا پهنای پنل عوض شود؛ دوبار کلیک: اندازهٔ پیش‌فرض',
  'Details panel width': 'پهنای پنل جزئیات',
  'Drag to resize the report strip height; double-click: default size': 'بکشید تا ارتفاع نوار گزارش‌ها عوض شود؛ دوبار کلیک: اندازهٔ پیش‌فرض',
  'Report strip height': 'ارتفاع نوار گزارش‌ها',
  'Waiting for you, collapsed': 'منتظر شما، جمع‌شده',
  '100%': '۱۰۰٪',

  // ---------- archive: tiles, stats, cards (SCRIPT, client-side)
  'Running': 'در حال اجرا',
  'Runs done': 'کارهای انجام‌شده',
  'Runs with findings': 'کارهای دارای ایراد',
  'Time spent': 'زمان صرف‌شده',
  'No data.': 'داده‌ای نیست.',
  ' runs · avg ': ' اجرا · میانگین ',
  ' tokens · total time ': ' توکن · مدت کل ',
  ' · avg time ': ' · میانگین مدت ',
  ' runs)': ' اجرا)',
  'Total tokens used (all time)': 'مجموع توکن مصرف‌شده (کل)',
  'Tokens used today': 'توکن مصرف‌شده امروز',
  'Tokens and time by agent': 'توکن و زمان به تفکیک ایجنت',
  'Tokens and runs by model': 'توکن و اجرا به تفکیک مدل',
  'Runs by project': 'اجرا به تفکیک پروژه',
  'Tokens used in the last 7 days': 'توکن مصرف‌شده در ۷ روز اخیر',
  'No agent is working right now.': 'هیچ ایجنتی همین الان در حال کار نیست.',
  'Project:': 'پروژه:',
  'Started:': 'شروع:',
  'Steps:': 'گام‌ها:',
  'so-far-tick': 'تا اینجا',
  'Finished:': 'پایان:',
  'Command:': 'دستور:',
  'Previous': 'قبلی',
  'Next': 'بعدی',
  'No agent has done any work yet.': 'هنوز هیچ ایجنتی کاری انجام نداده است.',
  'Nothing matches this search.': 'چیزی با این جستجو پیدا نشد.',
  'No agent is defined yet.': 'هنوز ایجنتی تعریف نشده است.',
  'All agents': 'همهٔ ایجنت‌ها',

  // ---------- archive: page shell (Node-rendered)
  'Today’s office ←': 'دفتر امروز ←',
  'Every task ever given to an agent: what was asked, which model did it, and what came back.':
    'هر کاری که به یک ایجنت سپرده شده: چه چیزی خواسته شده، کدام مدل انجامش داده و چه نتیجه‌ای برگشته.',
  'Usage stats': 'آمار مصرف',
  'Running right now': 'هم‌اکنون در حال اجرا',
  'This page asks the local server for fresh state every 1.5 seconds; it does not move until something actually changes.':
    'این صفحه هر ۱٫۵ ثانیه از سرور محلی وضعیت تازه می‌گیرد؛ تا وقتی چیزی عوض نشود، صفحه تکان نمی‌خورد.',
  'This page refreshes itself every few seconds and is rebuilt on every logged event.':
    'این صفحه هر چند ثانیه خودش را تازه می‌کند و با هر رویداد دوباره ساخته می‌شود.',
  'Search tasks, files and findings…': 'جستجو در کارها، فایل‌ها و ایرادها…',
  'Search': 'جستجو',
  'Filter by agent': 'فیلتر بر اساس ایجنت',
  'Filter by project': 'فیلتر بر اساس پروژه',
  'Filter by result': 'فیلتر بر اساس نتیجه',
  'Any result': 'هر نتیجه‌ای',

  // ---------- rail: dismissing a question, the answered history; strings that were
  // hard-coded English (wall boards, gate labels) and now go through T()
  'Dismiss': 'کنار گذاشتن',
  'Click again to dismiss': 'برای کنار گذاشتن دوباره بزنید',
  'Click again to dismiss ': 'برای کنار گذاشتن دوباره بزنید ',
  'Dismiss all older than 24 h ': 'کنار گذاشتن همهٔ قدیمی‌تر از ۲۴ ساعت ',
  'Close without answering, for example when it was settled in the chat': 'بستن بدون پاسخ، مثلاً وقتی در چت حل شده است',
  'Nothing answered or dismissed yet.': 'هنوز چیزی پاسخ داده یا کنار گذاشته نشده.',
  'dismissed': 'کنار گذاشته شد',
  ' dismissed.': ' کنار گذاشته شد.',
  'read by the supervisor': 'سرپرست خوانده',
  'not read yet': 'هنوز خوانده نشده',
  ' older ones not shown': ' مورد قدیمی‌تر نمایش داده نمی‌شود',
  'Answered and dismissed': 'پاسخ‌داده‌شده و کنارگذاشته‌شده',
  'restart the dashboard server once to turn this on': 'برای فعال شدن این قابلیت، سرور داشبورد را یک بار دوباره راه‌اندازی کنید',
  'Gate ': 'دروازه ',
  ' failed': ' ناموفق',
  ' with findings': ' با ایراد',
  ' running · ': ' در کار · ',
  ' in': ' تحویل',
  'no open issue': 'بدون ایراد باز',
  'Last update': 'آخرین به‌روزرسانی',
  'Duration:': 'مدت:',
  '● Disconnected from server': '● بی‌ارتباط با سرور',

  // ---------- language switch itself
  'Language': 'زبان',

  // ---------- the company: header, campus, office strip (agent-company-page.cjs)
  'BOARD VIEW': 'نمای هیئت‌مدیره',
  'Campus': 'محوطه',
  'Org chart': 'چارت سازمانی',
  'Choose an office': 'انتخاب دفتر',
  'More': 'بیشتر',
  'Unassigned work': 'کارهای بی‌دفتر',
  'tok': 'توکن',
  // number units: the leading space is part of the Persian word, so "2.12 میلیون"
  'M': ' میلیون',
  'k': ' هزار',
  'USD': 'دلار',
  'n/a': 'نامشخص',
  'USD n/a': 'دلار نامشخص',
  'OK': 'تأیید',
  ' · new': ' · تازه',
  'RUNNING': 'در کار',
  'DONE': 'انجام‌شده',
  'AGENTS': 'ایجنت‌ها',
  'FINDINGS': 'ایرادها',
  'FAILED': 'ناموفق',
  'STOPPED': 'متوقف',
  'TIME': 'زمان',
  'TOKENS': 'توکن',
  ' is missing or unreadable': ' وجود ندارد یا خوانده نمی‌شود',
  ' is not a list': ' فهرست نیست',
  ' is not an object': ' شیء نیست',
  'project ': 'پروژهٔ ',
  ' names an unknown office ': ' دفتری نامشخص را نام می‌برد: ',
  'Unexpected error': 'خطای پیش‌بینی‌نشده',
  'Server error ': 'خطای سرور ',
  'Enter a whole number of tokens, for example 2000000': 'یک عدد صحیح برای توکن وارد کنید، مثلاً 2000000',
  'Enter an amount in USD, for example 25.50': 'مبلغ را به دلار وارد کنید، مثلاً 25.50',
  'USD takes at most 2 decimals': 'دلار حداکثر دو رقم اعشار می‌گیرد',
  'At most 1,000,000,000 tokens a month': 'حداکثر ۱٬۰۰۰٬۰۰۰٬۰۰۰ توکن در ماه',
  'At most 100,000 USD a month': 'حداکثر ۱۰۰٬۰۰۰ دلار در ماه',
  'The alert threshold is a whole percentage from 1 to 99': 'آستانهٔ هشدار یک درصد صحیح از ۱ تا ۹۹ است',
  'budget must be an object': 'بودجه باید یک شیء باشد',
  'the unassigned office has no budget of its own': 'دفتر «بی‌دفتر» بودجهٔ جداگانه ندارد',
  'the supervisor has no budget of its own: its chat tokens are not visible here': 'سرپرست بودجهٔ جداگانه ندارد: توکن‌های گفتگوی او اینجا دیده نمی‌شود',
  'bad office id': 'شناسهٔ دفتر نامعتبر است',
  'bad employee id': 'شناسهٔ کارمند نامعتبر است',
  'no such office: ': 'چنین دفتری نیست: ',
  'no such employee: ': 'چنین کارمندی نیست: ',
  'scope must be company, office or employee': 'محدوده باید شرکت، دفتر یا کارمند باشد',
  'origin': 'درخواست از همین صفحه نیست',
  'token': 'نشانهٔ صفحه منقضی شده؛ صفحه را دوباره باز کنید',
  'json only': 'فقط JSON پذیرفته می‌شود',
  'too large': 'درخواست بیش از حد بزرگ است',
  'bad json': 'JSON نامعتبر',
  'POST only': 'فقط POST پذیرفته می‌شود',
  'dashboard code too old': 'کد داشبورد قدیمی است؛ سرور را دوباره راه‌اندازی کنید',
  'Model prices are not set in model-prices.json': 'قیمت مدل‌ها در model-prices.json وارد نشده',
  ' runs have tokens but no price': ' اجرا توکن دارد ولی قیمت ندارد',
  ' of budget': ' از بودجه',
  'Budgets off': 'بودجه‌ها خاموش',
  'No budget set': 'بی‌بودجه',
  'Budget off': 'بودجه خاموش',
  'Monthly budget': 'بودجهٔ ماهانه',
  'monthly budget': 'بودجهٔ ماهانه',
  'Budget…': 'بودجه…',
  'working': 'در کار',
  'waiting': 'در انتظار',
  'paused': 'متوقف',
  'idle': 'بیکار',
  'Waiting': 'در انتظار',
  'Paused': 'متوقف',
  'Idle': 'بیکار',
  'Away': 'بیرون از دفتر',
  'Enter office →': 'ورود به دفتر ←',
  'Windows on the top floors: one per employee': 'پنجره‌های طبقات بالا: هر کارمند یکی',
  'Lavender kiosk = ': 'کیوسک بنفش = ',
  'Click a building to enter.': 'برای ورود روی ساختمان بزنید.',
  'Company summary': 'خلاصهٔ شرکت',
  'Company data was written by a newer dashboard (v': 'دادهٔ شرکت را داشبوردی جدیدتر نوشته است (نسخهٔ ',
  '). Editing is disabled.': '). ویرایش بسته است.',
  'Open from the live server to edit.': 'برای ویرایش، صفحه را از سرور زنده باز کنید.',
  'Company this month': 'شرکت در این ماه',
  'working now': 'هم‌اکنون در کار',
  'tokens of ': 'توکن از ',
  'tokens this month': 'توکن این ماه',
  ' runs unmeasured': ' اجرای اندازه‌گیری‌نشده',
  'company budget ': 'بودجهٔ شرکت ',
  'Budgets: ': 'بودجه‌ها: ',
  'on': 'روشن',
  'off — usage only, no alerts, no refusals': 'خاموش — فقط مصرف، بی‌هشدار، بی‌رد',
  'Click again to confirm': 'برای تأیید دوباره بزنید',
  'Turn off': 'خاموش کن',
  'Turn on': 'روشن کن',
  'Company budget…': 'بودجهٔ شرکت…',
  'Offices': 'دفترها',
  'Not seen yet: the supervisor stamps this with --answers or --heartbeat.': 'هنوز دیده نشده: سرپرست با ‎--answers یا ‎--heartbeat این را ثبت می‌کند.',
  'Away. Last seen ': 'غایب. آخرین حضور ',
  'Active. Last seen ': 'فعال. آخرین حضور ',
  '. Requests are read when the supervisor is next active.': '. درخواست‌ها دفعهٔ بعد که سرپرست فعال شود خوانده می‌شوند.',
  'Project names this month that no project claims: ': 'نام‌های پروژه در این ماه که به هیچ پروژه‌ای وصل نیستند: ',
  'HARD STOP': 'توقف قطعی',
  'retired: definition file removed': 'بازنشسته: فایل تعریف حذف شده',
  ' employees': ' کارمند',
  ' offices': ' دفتر',
  'Hide retired': 'پنهان کردن بازنشسته‌ها',
  'Show retired': 'نمایش بازنشسته‌ها',
  'Board · you': 'هیئت‌مدیره · شما',
  'Approves hires, budgets, commits and pushes': 'استخدام، بودجه، کامیت و پوش را تأیید می‌کند',
  'Supervisor · CEO': 'سرپرست · مدیرعامل',
  'The main chat session: starts every agent, asks you at the gates': 'جلسهٔ اصلی گفتگو: هر ایجنت را راه می‌اندازد و سر دروازه‌ها از شما می‌پرسد',
  'last seen ': 'آخرین حضور ',
  'not seen yet': 'هنوز دیده نشده',
  ' staff': ' نفر',
  'Head: the supervisor (CEO)': 'رئیس: سرپرست (مدیرعامل)',
  'No head named for this office': 'برای این دفتر رئیسی تعیین نشده',
  'Contractors': 'پیمانکاران',
  'None this month.': 'این ماه هیچ.',
  'paused or stopped by budget': 'متوقف یا بسته‌شده با بودجه',
  'tick on the bar = alert threshold': 'خط روی نوار = آستانهٔ هشدار',
  'Bar = this month’s spend against the budget': 'نوار = مصرف این ماه در برابر بودجه',
  'Budgets are off: usage only': 'بودجه‌ها خاموش‌اند: فقط مصرف',
  'the whole company': 'کل شرکت',
  'Monthly budget — ': 'بودجهٔ ماهانه — ',
  'Counted from the runs the supervisor logs, per calendar month. Saved in company/ and read by the supervisor at its next turn.':
    'از اجراهایی که سرپرست ثبت می‌کند، برای هر ماه تقویمی شمرده می‌شود. در company/ ذخیره می‌شود و سرپرست در نوبت بعدی‌اش آن را می‌خواند.',
  'Budget on': 'بودجه روشن',
  'Off keeps the numbers but shows usage only: no alerts, no refusals.': 'خاموش، عددها را نگه می‌دارد ولی فقط مصرف را نشان می‌دهد: بی‌هشدار، بی‌رد.',
  'Tokens per month': 'توکن در ماه',
  'Empty = no limit. 0 = nothing may be spent. Cache reads are not counted.': 'خالی = بی‌سقف. ۰ = هیچ مصرفی مجاز نیست. خواندن از کش شمرده نمی‌شود.',
  'USD per month': 'دلار در ماه',
  'From the prices in model-prices.json.': 'از قیمت‌های model-prices.json.',
  'Model prices are not set in model-prices.json: USD use shows n/a and cannot be checked.': 'قیمت مدل‌ها در model-prices.json وارد نشده: مصرف دلاری «نامشخص» نشان داده می‌شود و قابل بررسی نیست.',
  'Alert at (%)': 'هشدار در (٪)',
  'Hard stop at 100%': 'توقف قطعی در ۱۰۰٪',
  'The supervisor’s --budget-check then refuses to start agents here. The dashboard cannot stop a running agent.':
    'آن‌وقت ‎--budget-check سرپرست راه‌اندازی ایجنت را اینجا رد می‌کند. داشبورد نمی‌تواند ایجنتِ در حال کار را متوقف کند.',
  'Remove budget': 'حذف بودجه',
  'Cancel': 'انصراف',
  'Save': 'ذخیره',
  'Saved. The supervisor reads it at its next turn.': 'ذخیره شد. سرپرست در نوبت بعدی‌اش آن را می‌خواند.',
  'Not saved: ': 'ذخیره نشد: ',
  'Restart the dashboard server to edit company data.': 'برای ویرایش دادهٔ شرکت، سرور داشبورد را دوباره راه‌اندازی کنید.',
  ' more in other offices': ' مورد دیگر در دفترهای دیگر',
  'Lead desk': 'میز رئیس',
  'In ': 'در ',
  'Overflow': 'بی‌میز',
  'no free desk: ': 'میز خالی نیست: ',
  'The supervisor started this run although the budget check said stop': 'سرپرست این اجرا را با وجود «توقف» در بررسی بودجه شروع کرد',
  'started despite stop': 'با وجود توقف شروع شد',
  'No company set up': 'شرکتی تعریف نشده',
  'The dashboard works as a single office until a company is set up. Create one with': 'تا وقتی شرکتی تعریف نشود، داشبورد یک دفتر تنهاست. برای ساختن شرکت:',
  // ---------- v1.0: the Activity screen, the archive title, the data folder
  'Each agent is defined in a Markdown file in the agent folders, and their shared rules are in <code>AGENT-RULES.md</code>. Agents can build a new agent themselves, under the same rules.': 'تعریف هر ایجنت یک فایل ‎.md در پوشه‌های ایجنت است و قانون‌های مشترکشان در <code>AGENT-RULES.md</code>. ایجنت‌ها خودشان هم می‌توانند ایجنت تازه بسازند، با همین قانون‌ها.',
  'agent with no definition in the agent folders': 'ایجنت بدون تعریف در پوشه‌های ایجنت',
  'agent names with no definition in the agent folders, this month': 'نام ایجنت‌هایی که در پوشه‌های ایجنت تعریفی ندارند، در این ماه',
  'no company configured: run arsenale log --company-init first': 'شرکتی تعریف نشده: اول ‎arsenale log --company-init‎ را اجرا کنید',
  'Deleting the company folder in the data folder brings this view back.': 'حذف پوشهٔ شرکت در پوشهٔ داده‌ها همین نما را برمی‌گرداند.',
  'Archive': 'بایگانی',
  'Activity': 'فعالیت',
  'Everyone': 'همه',
  'System': 'سیستم',
  'Everything': 'همهٔ موارد',
  'Runs': 'اجراها',
  'Questions': 'پرسش‌ها',
  'Decisions': 'تصمیم‌ها',
  'Company & budgets': 'شرکت و بودجه',
  'Newest first. Lines marked “derived” are read from the run records, questions and decisions; the others are the company log (company/activity.jsonl).': 'جدیدترین بالا. سطرهای «برگرفته» از سوابق اجرا، پرسش‌ها و تصمیم‌ها خوانده می‌شوند؛ بقیه از دفتر شرکت‌اند (company/activity.jsonl).',
  'Nothing recorded in these days.': 'در این روزها چیزی ثبت نشده.',
  'Show 7 more days': 'نمایش ۷ روز دیگر',
  ' older': ' مورد قدیمی‌تر',
  'started': 'شروع کرد',
  'asked': 'پرسید',
  'open question': 'پرسش باز',
  'decided': 'تصمیم گرفت',
  'run': 'اجرا',
  'gate': 'پرسش',
  'decision': 'تصمیم',
  'budget': 'بودجه',
  'company': 'شرکت',
  'derived': 'برگرفته',

  // ---------- 1.0 (everyone-page.cjs): plain words. task = وظیفه, job = کار,
  // team member = عضو تیم, your assistant = دستیار شما, deliverable = تحویلی
  'Your assistant': 'دستیار شما',
  'under a minute': 'کمتر از یک دقیقه',
  ' h': ' ساعت',
  ' KB': ' کیلوبایت',
  ' MB': ' مگابایت',
  'Copied.': 'کپی شد.',
  'Click again to confirm: ': 'برای تأیید دوباره بزنید: ',
  'Open the live dashboard (arsenale serve) to use this screen.': 'برای این صفحه، داشبورد زنده را باز کنید (arsenale serve).',
  'Your assistant decides': 'دستیار شما تصمیم می‌گیرد',
  'Tasks': 'وظیفه‌ها',
  'Tasks belong to a company. Set up your company first.': 'وظیفه‌ها مال یک شرکت‌اند. اول شرکت خود را راه بیندازید.',
  'Set up your company': 'راه‌اندازی شرکت',
  'Done': 'انجام‌شده',
  'To do': 'برای انجام',
  'Later': 'بعداً',
  'In progress': 'در جریان',
  'Blocked': 'گیرکرده',
  'Cancelled': 'لغوشده',
  'Every office': 'همهٔ دفترها',
  'New task': 'وظیفهٔ تازه',
  'Writing a task starts nothing. Your assistant picks it up the next time you talk to it.': 'نوشتن یک وظیفه چیزی را راه نمی‌اندازد. دستیار شما دفعهٔ بعد که با او حرف بزنید آن را برمی‌دارد.',
  'No tasks yet. Write one, and your assistant will see it next time.': 'هنوز وظیفه‌ای نیست. یکی بنویسید تا دستیار شما دفعهٔ بعد ببیند.',
  'Start from an example': 'شروع از یک نمونه',
  'seen by your assistant ': 'دستیار شما دید ',
  'comments': 'یادداشت',
  'Your assistant is not connected yet': 'دستیار شما هنوز وصل نشده',
  'My assistant decides': 'دستیارم تصمیم بگیرد',
  'Office: ': 'دفتر: ',
  'Title': 'عنوان',
  'Details': 'جزئیات',
  'For': 'برای',
  'Due': 'موعد',
  'Optional. A date in the past is allowed and shown in red.': 'اختیاری. تاریخ گذشته هم پذیرفته می‌شود و قرمز نشان داده می‌شود.',
  'Web links, one per line': 'پیوندهای وب، هر خط یکی',
  'File paths, one per line': 'مسیر فایل‌ها، هر خط یکی',
  'Shown as text with "Copy path". Arsenale never opens a file.': 'به‌صورت متن با «کپی مسیر» نشان داده می‌شود. آرسناله هیچ‌وقت فایلی را باز نمی‌کند.',
  'I want to check it before it is done': 'می‌خواهم پیش از تمام‌شدن آن را بررسی کنم',
  'Create task': 'ساختن وظیفه',
  'Loading…': 'در حال بارگذاری…',
  'needs your check': 'بررسی شما لازم است',
  'Close': 'بستن',
  'This date has passed': 'این تاریخ گذشته است',
  'Your assistant picks this up the next time you talk to it.': 'دستیار شما دفعهٔ بعد که با او حرف بزنید این را برمی‌دارد.',
  'Copy a message for your assistant': 'کپی پیامی برای دستیارتان',
  'Change state': 'تغییر وضعیت',
  'Links': 'پیوندها',
  'Copy path': 'کپی مسیر',
  'Jobs': 'کارها',
  'No summary given': 'خلاصه‌ای داده نشده',
  'Deliverables': 'تحویلی‌ها',
  'Comments': 'یادداشت‌ها',
  'No comments yet.': 'هنوز یادداشتی نیست.',
  'Your comment': 'یادداشت شما',
  'Add comment': 'افزودن یادداشت',
  'Hire proposal': 'پیشنهاد استخدام',
  'Approval: ': 'تأیید: ',
  'Approval': 'تأیید',
  'Choice': 'انتخاب',
  'Release question': 'پرسش انتشار',
  'Question': 'پرسش',
  'Approvals': 'تأییدها',
  'What your assistant asked you. An answer here reaches it the next time it checks.': 'آنچه دستیار شما از شما پرسیده. پاسخ اینجا دفعهٔ بعد که سر بزند به او می‌رسد.',
  'Answered lately': 'پاسخ‌های اخیر',
  'from your phone': 'از گوشی شما',
  'Answer: ': 'پاسخ: ',
  'Closed without an answer': 'بی‌پاسخ بسته شد',
  'via your assistant': 'از طریق دستیار شما',
  'What: ': 'چه: ',
  'Where: ': 'کجا: ',
  'Name': 'نام',
  'Short id': 'شناسهٔ کوتاه',
  'Why: ': 'چرا: ',
  'Hire as proposed': 'استخدام همان‌طور که پیشنهاد شده',
  'Edit and hire': 'ویرایش و استخدام',
  'Approve payment': 'تأیید پرداخت',
  'Your answer': 'پاسخ شما',
  'Close without answering': 'بستن بدون پاسخ',
  'Team': 'تیم',
  'No team members yet. Install an office pack or hire someone.': 'هنوز عضوی در تیم نیست. یک بستهٔ دفتر نصب کنید یا کسی را استخدام کنید.',
  'Hire': 'استخدام',
  'A team member is a role your assistant takes on for a task: it reads the member\'s instructions and logs the job under that name. Only Claude Code can also run them as separate helpers.': 'عضو تیم نقشی است که دستیار شما برای یک وظیفه به عهده می‌گیرد: دستورهای آن عضو را می‌خواند و کار را به نام او ثبت می‌کند. فقط Claude Code می‌تواند آن‌ها را جدا هم اجرا کند.',
  'No office': 'بی‌دفتر',
  'Retired': 'بازنشسته',
  'Active': 'فعال',
  'job this month': 'کار در این ماه',
  'jobs this month': 'کار در این ماه',
  'asks first: ': 'اول می‌پرسد: ',
  'never: ': 'هرگز: ',
  'Overview': 'نمای کلی',
  'Allowed actions': 'کارهای مجاز',
  'Instructions': 'دستورها',
  'History': 'تاریخچه',
  'Job title': 'عنوان شغلی',
  'Reports to': 'گزارش به',
  'Strength': 'توان',
  'This month': 'این ماه',
  'jobs': 'کار',
  'job': 'کار',
  'Retire': 'بازنشسته کردن',
  'Bring back': 'برگرداندن',
  'This file belongs to another tool (for example Claude Code). Editing it keeps a backup.': 'این فایل مال ابزار دیگری است (مثلاً Claude Code). ویرایش آن یک نسخهٔ پشتیبان نگه می‌دارد.',
  'Edit instructions': 'ویرایش دستورها',
  'No earlier versions yet. Every edit keeps the version before it.': 'هنوز نسخهٔ قبلی‌ای نیست. هر ویرایش نسخهٔ پیش از خود را نگه می‌دارد.',
  'Restore': 'بازگرداندن',
  'Action': 'کار',
  'Rule': 'قاعده',
  'Phone approvals': 'تأیید با گوشی',
  'changed for this member': 'برای این عضو تغییر کرده',
  'Reset': 'بازنشانی',
  'from defaults': 'از پیش‌فرض',
  'computer only': 'فقط روی رایانه',
  'allowed': 'مجاز',
  'Allowed': 'مجاز',
  'Ask me first': 'اول از من بپرس',
  'Never': 'هرگز',
  'What': 'چه کاری',
  'Limits': 'محدودیت‌ها',
  'Edit team member': 'ویرایش عضو تیم',
  'Hire a team member': 'استخدام عضو تیم',
  'Display name': 'نام نمایشی',
  'Short id (letters, digits, hyphens; used in files)': 'شناسهٔ کوتاه (حرف لاتین، رقم و خط تیره؛ در نام فایل)',
  'Left empty, it is made from a Latin name.': 'اگر خالی بماند، از نام لاتین ساخته می‌شود.',
  'The head of the office': 'رئیس دفتر',
  'What they do, in one line': 'کارش در یک خط',
  '10 to 300 characters.': '۱۰ تا ۳۰۰ نویسه.',
  'Instructions, in plain words': 'دستورها، به زبان ساده',
  'Light': 'سبک',
  'Standard': 'معمولی',
  'Strong': 'قوی',
  'Light is quick and cheap, Strong is for hard work. Claude Code uses this; other assistants ignore it.': 'سبک تند و ارزان است، قوی برای کار سخت. Claude Code از این استفاده می‌کند؛ دستیارهای دیگر نادیده‌اش می‌گیرند.',
  'Monthly budget in USD (optional)': 'بودجهٔ ماهانه به دلار (اختیاری)',
  'In Claude Code': 'در Claude Code',
  'Create and edit files': 'ساختن و ویرایش فایل',
  'Search the web': 'جست‌وجو در وب',
  'Run commands (advanced)': 'اجرای فرمان (پیشرفته)',
  'This file belongs to another tool. Edit it anyway; a backup will be kept.': 'این فایل مال ابزار دیگری است. با این حال ویرایش شود؛ نسخهٔ پشتیبان نگه داشته می‌شود.',
  'This is the file Arsenale will write. Nothing is saved until you press the button.': 'این فایلی است که آرسناله می‌نویسد. تا دکمه را نزنید چیزی ذخیره نمی‌شود.',
  'Back': 'بازگشت',
  'Weekly newsletter': 'خبرنامهٔ هفتگی',
  'Writes our weekly newsletter from the notes I leave in the workspace folder. Short, friendly, three sections. Never sends it: it saves the draft and tells me.': 'خبرنامهٔ هفتگی ما را از یادداشت‌هایی که در پوشهٔ کار می‌گذارم می‌نویسد. کوتاه، صمیمی، سه بخش. هیچ‌وقت آن را نمی‌فرستد: پیش‌نویس را ذخیره می‌کند و به من خبر می‌دهد.',
  'Customer replies': 'پاسخ به مشتری',
  'Drafts replies to the customer messages I paste in, in our calm and friendly tone. Never sends them.': 'برای پیام‌هایی که از مشتری می‌چسبانم با لحن آرام و صمیمی ما پیش‌نویس پاسخ می‌نویسد. هیچ‌وقت نمی‌فرستد.',
  'Meeting notes': 'صورت‌جلسه',
  'Turns my rough meeting notes into tidy minutes with a to-do list and who does what, by role.': 'یادداشت‌های خام جلسه را به صورت‌جلسهٔ مرتب با فهرست کارها و اینکه چه کسی (بر اساس نقش) چه می‌کند تبدیل می‌کند.',
  'Documents': 'سندها',
  'Images': 'تصویرها',
  'Text': 'متن',
  'Document': 'سند',
  'Image': 'تصویر',
  'Link': 'پیوند',
  'File': 'فایل',
  'Deliverables your team registers appear here.': 'آنچه تیم شما تحویل و ثبت کند اینجا می‌آید.',
  'File no longer there': 'فایل دیگر آنجا نیست',
  'link only': 'فقط پیوند',
  'Stored copies: ': 'نسخه‌های نگه‌داشته: ',
  'over 2 GB: consider deleting old ones': 'بیش از ۲ گیگابایت: پاک‌کردن نسخه‌های قدیمی را در نظر بگیرید',
  'From the job: ': 'از کار: ',
  'No preview for this type.': 'برای این نوع پیش‌نمایشی نیست.',
  'Download': 'دریافت',
  'Not copied: ': 'کپی نشد: ',
  'protected file': 'فایل محافظت‌شده',
  'outside your deliverable folders': 'بیرون از پوشه‌های تحویلی شما',
  'file no longer there': 'فایل دیگر آنجا نیست',
  'type not previewed': 'این نوع پیش‌نمایش ندارد',
  'not a file': 'فایل نیست',
  'not a valid image': 'تصویر معتبری نیست',
  'not plain text': 'متن ساده نیست',
  'not a valid PDF': 'پی‌دی‌اف معتبری نیست',
  'Settings': 'تنظیمات',
  'Connect your assistant': 'وصل‌کردن دستیار',
  'Office packs': 'بسته‌های دفتر',
  'Safety': 'ایمنی',
  'Notifications': 'اعلان‌ها',
  'Privacy and security': 'حریم خصوصی و امنیت',
  'Connect the assistant you use, and it logs its work here by itself. Arsenale shows you every change before it makes one, and keeps a backup.': 'دستیاری را که به کار می‌برید وصل کنید تا کارش را خودش اینجا ثبت کند. آرسناله هر تغییری را پیش از انجام به شما نشان می‌دهد و نسخهٔ پشتیبان نگه می‌دارد.',
  'Connected assistants': 'دستیارهای وصل',
  'None yet. After connecting, say "Say hello to Arsenale" in your assistant.': 'هنوز هیچ. پس از وصل‌کردن، در دستیارتان بنویسید «به آرسناله سلام کن».',
  'last call ': 'آخرین تماس ',
  'calls today': 'تماس امروز',
  'quiet': 'ساکت',
  'A forgotten assistant can connect again; this only clears what Arsenale remembers about it.': 'دستیار فراموش‌شده می‌تواند دوباره وصل شود؛ این فقط آنچه آرسناله از او به یاد دارد را پاک می‌کند.',
  'Forget': 'فراموش کن',
  'The name an assistant gives is a label, not proof of who it is.': 'نامی که دستیار می‌دهد برچسب است، نه گواه هویت.',
  'Custom instructions': 'دستورهای سفارشی',
  'Some assistants ignore the instructions Arsenale sends. Paste this into your assistant\'s custom instructions:': 'برخی دستیارها دستورهای آرسناله را نادیده می‌گیرند. این را در دستورهای سفارشی دستیارتان بچسبانید:',
  'Copy': 'کپی',
  'Advanced: MCP over HTTP': 'پیشرفته: MCP روی HTTP',
  'For assistants that accept only a web address. It works only while this dashboard runs, and needs a secret token on every call.': 'برای دستیارهایی که فقط نشانی وب می‌پذیرند. فقط وقتی این داشبورد روشن است کار می‌کند و در هر تماس یک نشانهٔ محرمانه لازم دارد.',
  'On, at ': 'روشن، در ',
  'Off. To turn it on, set the environment variable ARSENALE_MCP_TOKEN to a random value of 32 or more characters and restart the dashboard.': 'خاموش. برای روشن‌کردن، متغیر محیطی ARSENALE_MCP_TOKEN را به یک مقدار تصادفی با ۳۲ نویسه یا بیشتر بدهید و داشبورد را از نو راه بیندازید.',
  'Make a random token to copy': 'ساختن یک نشانهٔ تصادفی برای کپی',
  'The token is stored in your assistant\'s settings in plain text. Anyone who can read those files can log as your assistant, but cannot answer or approve anything.': 'این نشانه در تنظیمات دستیار شما به‌صورت متن ساده ذخیره می‌شود. هر کس آن فایل‌ها را بخواند می‌تواند به جای دستیار شما ثبت کند، اما نمی‌تواند به چیزی پاسخ دهد یا چیزی را تأیید کند.',
  'experimental': 'آزمایشی',
  'Connected · last call ': 'وصل · آخرین تماس ',
  'Not connected': 'وصل نیست',
  'Copy command': 'کپی فرمان',
  'Open in Cursor': 'باز کردن در Cursor',
  'Open in VS Code': 'باز کردن در VS Code',
  'Add to its settings file…': 'افزودن به فایل تنظیمات آن…',
  'Test': 'آزمایش',
  'Show what will be added': 'نشان بده چه افزوده می‌شود',
  'Connected. Arsenale heard from your assistant.': 'وصل شد. آرسناله صدای دستیار شما را شنید.',
  'Not yet. Check the steps.': 'هنوز نه. گام‌ها را بررسی کنید.',
  'Now type in your assistant: Say hello to Arsenale. Waiting…': 'اکنون در دستیارتان بنویسید: «به آرسناله سلام کن». در انتظار…',
  'Other MCP clients': 'دیگر برنامه‌های MCP',
  'about ': 'حدود ',
  ' (estimated)': ' (برآورد)',
  'Included in your plan': 'در اشتراک شما',
  'Your assistant did not report usage': 'دستیار شما مصرف را گزارش نکرده',
  'What was done': 'آنچه انجام شد',
  'Use the Arsenale tools: at the start of a conversation call hello and get_inbox; call start_job before distinct work, log_step for each step, finish_job with a plain summary; ask_you when I may be away; check_action before sending, posting, paying, deleting or sharing anything.': 'از ابزارهای آرسناله استفاده کن: در آغاز هر گفت‌وگو hello و get_inbox را صدا بزن؛ پیش از هر کار جدا start_job، برای هر گام log_step، و در پایان finish_job با خلاصه‌ای ساده؛ وقتی ممکن است نباشم ask_you؛ و پیش از فرستادن، انتشار، پرداخت، پاک‌کردن یا هم‌رسانی هر چیز check_action.',
  'Arsenale is already in this file.': 'آرسناله از قبل در این فایل هست.',
  'File: ': 'فایل: ',
  'Before:': 'پیش از تغییر:',
  '(no file yet)': '(هنوز فایلی نیست)',
  'After:': 'پس از تغییر:',
  'Write this change (a backup is kept)': 'این تغییر نوشته شود (نسخهٔ پشتیبان نگه داشته می‌شود)',
  'Restart Claude Desktop after the change.': 'پس از تغییر، Claude Desktop را از نو باز کنید.',
  'Use MCP or the CLAUDE.md block with the hooks, not both: both log every job twice.': 'یا MCP یا بخش CLAUDE.md با قلاب‌ها، نه هر دو: با هر دو هر کار دو بار ثبت می‌شود.',
  'Any client that starts a local MCP server: give it this command. Clients that take only a URL can use MCP over HTTP (Advanced).': 'هر برنامه‌ای که سرور MCP محلی را راه می‌اندازد: این فرمان را به آن بدهید. برنامه‌هایی که فقط نشانی می‌گیرند می‌توانند از MCP روی HTTP (پیشرفته) استفاده کنند.',
  'ChatGPT connects only to MCP servers on the public internet, and Arsenale stays on this computer. Use "Copy a message for your assistant" on a task instead. Help is wanted on a safe way (see CONTRIBUTING.md).': 'ChatGPT فقط به سرورهای MCP روی اینترنت عمومی وصل می‌شود و آرسناله روی همین رایانه می‌ماند. به جای آن، روی وظیفه از «کپی پیامی برای دستیارتان» استفاده کنید. برای یافتن راهی امن کمک خواسته شده (CONTRIBUTING.md).',
  'Ready-made teams for an office. Installing one adds the office and its team members; removing it keeps every file you changed and all history.': 'تیم‌های آماده برای یک دفتر. نصب، دفتر و اعضایش را می‌افزاید؛ حذف، هر فایلی را که تغییر داده‌اید و همهٔ تاریخچه را نگه می‌دارد.',
  'Set up your company first: the wizard installs the packs you choose.': 'اول شرکت خود را راه بیندازید: راهنمای راه‌اندازی بسته‌هایی را که انتخاب کنید نصب می‌کند.',
  'team members': 'عضو تیم',
  'Installed': 'نصب‌شده',
  'Remove': 'حذف',
  'Update': 'به‌روزرسانی',
  'Needs a newer Arsenale': 'آرسنالهٔ تازه‌تری لازم دارد',
  'Install': 'نصب',
  'Keep yours': 'مال خودتان بماند',
  'Install as a copy': 'نصب به‌صورت نسخهٔ دوم',
  'Only the packs that come with Arsenale can be installed. A pack is instructions your assistant follows, so packs from elsewhere are not accepted.': 'فقط بسته‌هایی که همراه آرسناله می‌آیند نصب می‌شوند. بسته دستورهایی است که دستیار شما دنبال می‌کند، پس بستهٔ جای دیگر پذیرفته نمی‌شود.',
  'What your team may do that leaves this computer. "Ask me first" sends you an approval before the action.': 'کارهایی از تیم شما که از این رایانه بیرون می‌رود. «اول از من بپرس» پیش از کار یک درخواست تأیید برایتان می‌فرستد.',
  'Safety rules written by a newer Arsenale: everything asks first, and editing is off.': 'قواعد ایمنی را آرسنالهٔ تازه‌تری نوشته: همه‌چیز اول می‌پرسد و ویرایش خاموش است.',
  'Send a message': 'فرستادن پیام',
  'Post or publish': 'انتشار یا پست',
  'Pay or buy': 'پرداخت یا خرید',
  'Delete or overwrite': 'پاک‌کردن یا رونویسی',
  'Share outside': 'هم‌رسانی با بیرون',
  'Change accounts or sign up': 'تغییر حساب یا ثبت‌نام',
  'Anything else that leaves this computer': 'هر چیز دیگری که از این رایانه بیرون می‌رود',
  'email, chat, SMS, a reply to a customer': 'ایمیل، گفت‌وگو، پیامک، پاسخ به مشتری',
  'social media, website, review sites, public comments': 'شبکه‌های اجتماعی، وب‌سایت، سایت‌های نقد، نظر عمومی',
  'payments, orders, subscriptions, transfers': 'پرداخت، سفارش، اشتراک، انتقال پول',
  'files, records, emails; overwriting a file not made in this job': 'فایل، رکورد، ایمیل؛ رونویسی فایلی که در این کار ساخته نشده',
  'uploading files, sharing links or documents': 'بارگذاری فایل، هم‌رسانی پیوند یا سند',
  'creating accounts, accepting terms, changing settings or passwords': 'ساختن حساب، پذیرفتن شرایط، تغییر تنظیمات یا گذرواژه',
  'Arsenale asks your assistant to check first and records what happened. It cannot block your assistant\'s own tools. To block an action for certain, also switch it off in your assistant\'s settings.': 'آرسناله از دستیار شما می‌خواهد اول بپرسد و آنچه رخ داد را ثبت می‌کند. نمی‌تواند ابزارهای خود دستیار را ببندد. برای بستن قطعی یک کار، آن را در تنظیمات دستیارتان هم خاموش کنید.',
  'On this computer': 'روی این رایانه',
  'Your browser shows a notification when your assistant asks you something, when a task waits for you, or when a budget alert comes in, while this page is open in a tab.': 'تا وقتی این صفحه در یک زبانه باز است، مرورگر شما وقتی دستیارتان چیزی می‌پرسد، وظیفه‌ای منتظر شماست یا هشدار بودجه می‌رسد، اعلان نشان می‌دهد.',
  'Desktop notifications': 'اعلان روی رایانه',
  'Allow notifications in this browser': 'اجازهٔ اعلان در این مرورگر',
  'Blocked in the browser settings': 'در تنظیمات مرورگر بسته شده',
  'This browser has no notifications': 'این مرورگر اعلان ندارد',
  'On your phone': 'روی گوشی شما',
  'Your computer must be on and Arsenale running. If it is asleep, your tap is picked up when it wakes, if the request has not expired.': 'رایانهٔ شما باید روشن و آرسناله در حال اجرا باشد. اگر در خواب باشد، ضربهٔ شما وقتی بیدار شود دریافت می‌شود، به شرط آنکه درخواست منقضی نشده باشد.',
  'Secrets are read only from environment variables, never from a file: ARSENALE_PHONE_KEY (32+ characters) signs the buttons; ARSENALE_TELEGRAM_TOKEN, ARSENALE_NTFY_TOKEN, ARSENALE_PUSHOVER_TOKEN and ARSENALE_PUSHOVER_USER for the channels. Set them, then restart the dashboard.': 'رمزها فقط از متغیرهای محیطی خوانده می‌شوند، هیچ‌وقت از فایل: ARSENALE_PHONE_KEY (۳۲ نویسه یا بیشتر) دکمه‌ها را امضا می‌کند؛ ARSENALE_TELEGRAM_TOKEN، ARSENALE_NTFY_TOKEN، ARSENALE_PUSHOVER_TOKEN و ARSENALE_PUSHOVER_USER برای کانال‌ها. آن‌ها را تنظیم و داشبورد را از نو راه بیندازید.',
  'Signing key: ': 'کلید امضا: ',
  'set': 'تنظیم شده',
  'not set: messages are sent without buttons': 'تنظیم نشده: پیام‌ها بدون دکمه فرستاده می‌شوند',
  'On': 'روشن',
  'Off': 'خاموش',
  'Last sent: ': 'آخرین ارسال: ',
  'last decision: ': 'آخرین تصمیم: ',
  'invalid messages ignored today': 'پیام نامعتبر امروز نادیده گرفته شد',
  'Send test': 'ارسال آزمایشی',
  'Send a test first': 'اول یک پیام آزمایشی بفرستید',
  'Details mode: show the question and Approve / Decline buttons': 'حالت جزئیات: نشان‌دادن پرسش و دکمه‌های تأیید و رد',
  'The ntfy server you use sees the question text. A server of your own keeps it private.': 'سرور ntfy که به کار می‌برید متن پرسش را می‌بیند. سرور خودتان آن را خصوصی نگه می‌دارد.',
  'Telegram sees the question text; bot chats are not end-to-end encrypted.': 'تلگرام متن پرسش را می‌بیند؛ گفت‌وگو با ربات رمزگذاری سرتاسری ندارد.',
  'Pushover only notifies: no buttons. Pushover sees the message.': 'Pushover فقط خبر می‌دهد: بدون دکمه. Pushover پیام را می‌بیند.',
  'Server: ': 'سرور: ',
  'subscribe to: ': 'مشترک شوید در: ',
  'ntfy server': 'سرور ntfy',
  'Set up': 'راه‌اندازی',
  'Paired with one chat.': 'با یک گفت‌وگو جفت شده.',
  'Send this code to your bot within 10 minutes: ': 'این کد را تا ۱۰ دقیقه به ربات خود بفرستید: ',
  'Create a bot with BotFather, set its token, then pair.': 'با BotFather یک ربات بسازید، نشانهٔ آن را تنظیم کنید و سپس جفت کنید.',
  'Pair a chat': 'جفت‌کردن گفت‌وگو',
  'Email notifications are not built yet (help wanted). Payments are never approved from a phone.': 'اعلان ایمیلی هنوز ساخته نشده (کمک خواسته شده). پرداخت هیچ‌وقت از گوشی تأیید نمی‌شود.',
  'A phone request expires after (minutes)': 'درخواست گوشی پس از این مدت منقضی می‌شود (دقیقه)',
  'Sign out all phones': 'خروج همهٔ گوشی‌ها',
  'Privacy': 'حریم خصوصی',
  'Everything stays on this computer. There is no account, no tracking and no telemetry.': 'همه‌چیز روی همین رایانه می‌ماند. نه حسابی هست، نه ردگیری، نه گزارش‌دهی پنهان.',
  'Arsenale itself makes no network call unless you turn one of these on:': 'آرسناله خودش هیچ تماس شبکه‌ای نمی‌گیرد، مگر یکی از این‌ها را روشن کنید:',
  'ntfy: the server you set (ntfy.sh unless you choose your own)': 'ntfy: سروری که تنظیم کنید (ntfy.sh مگر سرور خودتان را انتخاب کنید)',
  'Telegram: api.telegram.org': 'تلگرام: api.telegram.org',
  'Pushover: api.pushover.net': 'Pushover: api.pushover.net',
  'Web links in tasks and deliverables open in your browser only when you click them. Arsenale never fetches them.': 'پیوندهای وب در وظیفه‌ها و تحویلی‌ها فقط وقتی رویشان بزنید در مرورگرتان باز می‌شوند. آرسناله هیچ‌وقت آن‌ها را دریافت نمی‌کند.',
  'Security': 'امنیت',
  'Only this page can answer, approve, hire, set budgets or change the safety rules. Your assistant cannot, whatever it is told.': 'فقط این صفحه می‌تواند پاسخ دهد، تأیید کند، استخدام کند، بودجه بگذارد یا قواعد ایمنی را تغییر دهد. دستیار شما، هر چه به او گفته شود، نمی‌تواند.',
  'The command line trusts what it is told: a command that says "by board" is taken as you. Anything that runs as your user on this computer can do that.': 'خط فرمان به آنچه گفته شود اعتماد می‌کند: فرمانی که بگوید «by board» از طرف شما پذیرفته می‌شود. هر چیزی که با کاربر شما روی این رایانه اجرا شود می‌تواند چنین کند.',
  'The safety rules are a request to your assistant, not a lock: Arsenale cannot stop another program\'s tools.': 'قواعد ایمنی درخواستی از دستیار شماست، نه قفل: آرسناله نمی‌تواند ابزارهای برنامهٔ دیگری را متوقف کند.',
  'A file is copied into the deliverables store only from the folders you allowed, never a protected file (keys, passwords, licences).': 'فایل فقط از پوشه‌هایی که اجازه داده‌اید در انبار تحویلی‌ها کپی می‌شود، و هیچ‌وقت فایل محافظت‌شده (کلید، گذرواژه، مجوز).',
  'Arsenale never opens or runs a file. A file path is shown as text.': 'آرسناله هیچ‌وقت فایلی را باز یا اجرا نمی‌کند. مسیر فایل به‌صورت متن نشان داده می‌شود.',
  'Close (nothing is saved)': 'بستن (چیزی ذخیره نمی‌شود)',
  'Welcome to Arsenale': 'به آرسناله خوش آمدید',
  'Arsenale is a window on the work your AI assistant does: what it is doing now, what it asks you, and what it delivered. It never starts or stops your assistant.': 'آرسناله پنجره‌ای است رو به کاری که دستیار هوش مصنوعی شما می‌کند: الان چه می‌کند، چه از شما می‌پرسد و چه تحویل داده. هیچ‌وقت دستیار شما را راه نمی‌اندازد یا متوقف نمی‌کند.',
  'Everything stays on this computer. No account, no tracking.': 'همه‌چیز روی همین رایانه می‌ماند. نه حساب، نه ردگیری.',
  'To try it first on an invented company, run "arsenale demo" in a terminal: it opens a demo dashboard that is deleted when it stops.': 'برای آزمودن روی یک شرکت ساختگی، در پایانه «arsenale demo» را اجرا کنید: داشبورد نمایشی‌ای باز می‌شود که با بستنش پاک می‌شود.',
  'Set up my company': 'راه‌اندازی شرکتم',
  'About you': 'دربارهٔ شما',
  'Company or project name': 'نام شرکت یا پروژه',
  'What does it do? (optional)': 'چه کاری می‌کند؟ (اختیاری)',
  'How do you pay for your AI assistant?': 'هزینهٔ دستیار هوش مصنوعی خود را چطور می‌پردازید؟',
  'A monthly plan': 'اشتراک ماهانه',
  'for example a Pro or Plus subscription': 'مثلاً اشتراک Pro یا Plus',
  'Pay per use': 'پرداخت به اندازهٔ مصرف',
  'an API account billed by use': 'حساب API با صورت‌حساب بر اساس مصرف',
  'Not sure': 'مطمئن نیستم',
  'Pick the teams you want. Each comes with team members who prepare drafts and ask before anything leaves this computer.': 'تیم‌هایی را که می‌خواهید انتخاب کنید. هر کدام اعضایی دارد که پیش‌نویس آماده می‌کنند و پیش از بیرون‌رفتن هر چیز از این رایانه می‌پرسند.',
  'Budget': 'بودجه',
  'On a monthly plan you pay the same whatever you use, so Arsenale shows the time spent and keeps budgets off. You can set a limit in USD anyway.': 'با اشتراک ماهانه هر چه مصرف کنید همان را می‌پردازید، پس آرسناله زمان صرف‌شده را نشان می‌دهد و بودجه را خاموش نگه می‌دارد. با این حال می‌توانید سقفی به دلار بگذارید.',
  'Monthly limit in USD (empty: no limit)': 'سقف ماهانه به دلار (خالی: بی‌سقف)',
  'Alert at this percentage': 'هشدار در این درصد',
  'Ask before going over': 'پیش از گذشتن از سقف بپرس',
  'The limit is advisory: Arsenale cannot stop your assistant; it asks it to check first.': 'این سقف توصیه است: آرسناله نمی‌تواند دستیار شما را متوقف کند؛ از او می‌خواهد اول بررسی کند.',
  'Which do you use? You can pick more than one.': 'کدام را به کار می‌برید؟ می‌توانید بیش از یکی انتخاب کنید.',
  'Cannot connect yet: it needs a server on the internet.': 'هنوز وصل نمی‌شود: سروری روی اینترنت لازم دارد.',
  'In chat assistants a team member is a role your assistant takes on for a task. Only Claude Code can run them as separate helpers.': 'در دستیارهای گفت‌وگو، عضو تیم نقشی است که دستیار شما برای یک وظیفه به عهده می‌گیرد. فقط Claude Code می‌تواند آن‌ها را جدا اجرا کند.',
  'Your browser can tell you when your assistant asks you something, while this page is open.': 'تا وقتی این صفحه باز است، مرورگرتان می‌تواند خبر دهد که دستیارتان چیزی می‌پرسد.',
  'Phone approvals can be set up later in Settings.': 'تأیید با گوشی را بعداً در تنظیمات می‌توانید راه بیندازید.',
  'Review and create': 'بازبینی و ساختن',
  'Arsenale will create these files and folders, and nothing else:': 'آرسناله این فایل‌ها و پوشه‌ها را می‌سازد و هیچ چیز دیگری را:',
  'Try again': 'دوباره امتحان کنید',
  'Create': 'ساختن',
  'Follow the steps for your assistant, then press Test.': 'گام‌های دستیار خود را دنبال کنید و سپس آزمایش را بزنید.',
  'Skip for now': 'فعلاً بگذر',
  'Your company is set up. Give your first task, and your assistant sees it the next time you talk to it.': 'شرکت شما راه افتاد. اولین وظیفه را بدهید تا دستیارتان دفعهٔ بعد که با او حرف بزنید ببیند.',
  'Give your first task': 'دادن اولین وظیفه',
  'Your assistant asks you something': 'دستیار شما چیزی می‌پرسد',
  'A task is waiting for you': 'وظیفه‌ای منتظر شماست',
  'Budget alert': 'هشدار بودجه',
  'Today': 'امروز',
  'your team finished ': 'تیم شما تمام کرد: ',
  'in': 'در',
  'deliverables': 'تحویلی',
  'question waiting': 'پرسش در انتظار',
  'questions waiting': 'پرسش در انتظار',
  'Please check Arsenale for task ': 'لطفاً در آرسناله وظیفهٔ ',
  ' and start it.': ' را ببین و شروعش کن.',
  'Retired. Their history stays.': 'بازنشسته شد. تاریخچه‌اش می‌ماند.',
  'Restored. The version before is kept too.': 'بازگردانده شد. نسخهٔ پیش از آن هم نگه داشته شد.',
  'Removed.': 'حذف شد.',
  'Kept because you changed them: ': 'نگه داشته شد چون تغییرشان داده بودید: ',
  'Updated.': 'به‌روز شد.',
  'Installed: ': 'نصب شد: ',
  'kept yours: ': 'مال خودتان ماند: ',
  'Written. Backup: ': 'نوشته شد. نسخهٔ پشتیبان: ',
  'none (new file)': 'ندارد (فایل تازه)',
  'Restart your assistant, then press Test.': 'دستیار خود را از نو باز کنید و سپس آزمایش را بزنید.',
  'Test sent. Check that it arrived on your phone.': 'پیام آزمایشی فرستاده شد. ببینید به گوشی‌تان رسیده باشد.',
  'Saved.': 'ذخیره شد.',
  'Saved. Your assistant sees the change in its next conversation. Claude Code: restart the session.': 'ذخیره شد. دستیار شما تغییر را در گفت‌وگوی بعدی می‌بیند. Claude Code: نشست را از نو شروع کنید.',
  'Set up. Subscribe to the topic in the ntfy app on your phone, then send a test.': 'راه افتاد. در برنامهٔ ntfy گوشی‌تان مشترک این موضوع شوید و سپس پیام آزمایشی بفرستید.',
  'Review the hire proposal': 'بررسی پیشنهاد استخدام',
  'Details: tools & usage': 'جزئیات: ابزار و مصرف',
  'The dashboard works as a single office until a company is set up.': 'تا وقتی شرکتی راه نیفتاده، داشبورد یک دفتر تنهاست.',
  'Or from the command line:': 'یا از خط فرمان:',
  // ---------- the 1.0 redesign: tasks board, approvals letter, office room, finished work, settings, wizard, org chart
  'Finished work': 'کارهای انجام‌شده',
  'finished work': 'کار انجام‌شده',
  'Board': 'تابلو',
  'List': 'فهرست',
  'Show as': 'نمایش به شکل',
  'Working on it': 'در حال انجام',
  'Done this week': 'انجام‌شده در این هفته',
  'Stuck': 'گیر کرده',
  'Stuck: your assistant needs something': 'گیر کرده: دستیار شما به چیزی نیاز دارد',
  'Nothing here.': 'اینجا چیزی نیست.',
  'task needs you': 'کار منتظر شماست',
  'tasks need you': 'کار منتظر شماست',
  'is waiting for a yes or no.': 'منتظر یک بله یا نه است.',
  'are waiting for a yes or no.': 'منتظر یک بله یا نه هستند.',
  ' and ': ' و ',
  'Go to Approvals': 'رفتن به تأییدها',
  'Ready for you to check.': 'آماده‌ی بررسی شما.',
  'Started ': 'شروع: ',
  'Took ': 'زمان: ',
  'Yesterday': 'دیروز',
  'just now': 'همین حالا',
  ' minutes ago': ' دقیقه پیش',
  'an hour ago': 'یک ساعت پیش',
  ' hours ago': ' ساعت پیش',
  'Give this task': 'سپردن این کار',
  'Say what you need, as you would to a colleague.': 'بگویید چه می‌خواهید، همان‌طور که به یک همکار می‌گویید.',
  'What do you need?': 'چه می‌خواهید؟',
  'Anything they should know?': 'چیزی که باید بدانند؟',
  'Optional': 'اختیاری',
  'Add web links or file paths': 'افزودن پیوند وب یا مسیر فایل',
  'Quick ideas:': 'ایده‌های آماده:',
  'Who should do it?': 'چه کسی انجامش دهد؟',
  'Let my assistant choose': 'دستیارم انتخاب کند',
  'Anyone in ': 'هر کسی در ',
  'Me': 'خودم',
  'When is it due?': 'تا کی باید انجام شود؟',
  'A date in the past is allowed and shown in red.': 'تاریخ گذشته هم پذیرفته است و به رنگ قرمز نشان داده می‌شود.',
  'Ask me before it is finished': 'پیش از تمام شدن از من بپرس',
  'You see the result first': 'اول نتیجه را خودتان می‌بینید',
  'The task goes into your assistant\'s inbox. It is picked up the next time your assistant checks, usually when you open a chat.': 'کار به صندوق دستیار شما می‌رود. دستیار دفعه‌ی بعد که سر می‌زند آن را برمی‌دارد، معمولاً وقتی گفت‌وگویی باز می‌کنید.',
  'Edit': 'ویرایش',
  'Mark as done': 'انجام شد',
  'Open again': 'باز کردن دوباره',
  'is waiting for you': 'منتظر شماست',
  'Reply with a note': 'پاسخ با یادداشت',
  'Who does it: ': 'انجام‌دهنده: ',
  'What you asked for': 'آنچه خواستید',
  'What happened': 'چه گذشت',
  'newest first': 'تازه‌ترین بالا',
  'started: ': 'شروع کرد: ',
  'asked you: ': 'از شما پرسید: ',
  'You answered: ': 'پاسخ شما: ',
  'You wrote this task': 'این کار را شما نوشتید',
  'Your assistant wrote this task': 'این کار را دستیار شما نوشت',
  'Write a comment for ': 'نظری برای ',
  'Assigned to': 'سپرده به',
  'Created': 'ساخته شده',
  'by you, ': 'به دست شما، ',
  'by your assistant, ': 'به دست دستیار شما، ',
  'Nothing handed in yet.': 'هنوز چیزی تحویل نشده است.',
  'for the curious': 'برای کنجکاوها',
  'Task number: ': 'شماره‌ی کار: ',
  'Jobs: ': 'نوبت‌های کار: ',
  'Usage: ': 'مصرف: ',
  'tokens': 'توکن',
  'Seen by your assistant ': 'دستیار شما دید: ',
  'State': 'وضعیت',
  'Yes, go ahead': 'بله، انجام بده',
  'Not yet: ': 'هنوز نه: ',
  'thing your team would like your OK on.': 'مورد که تیم شما تأییدتان را می‌خواهد.',
  'things your team would like your OK on.': 'مورد که تیم شما تأییدتان را می‌خواهد.',
  'Nothing happens until you answer.': 'تا پاسخ ندهید هیچ اتفاقی نمی‌افتد.',
  'asked at ': 'پرسیده در ',
  'task: ': 'کار: ',
  'Leaves your computer': 'از رایانه بیرون می‌رود',
  'Stays on your computer': 'روی رایانه می‌ماند',
  'Deletes files': 'فایل حذف می‌کند',
  'Public': 'عمومی',
  'Message': 'پیام',
  'Money': 'پول',
  'Cannot be undone': 'برگشت‌ناپذیر',
  'Shared': 'هم‌رسانی',
  'Accounts': 'حساب‌ها',
  'Sending email or messages': 'فرستادن ایمیل یا پیام',
  'Posting online or on social media': 'انتشار در وب یا شبکه‌های اجتماعی',
  'Paying or spending money': 'پرداخت یا خرج کردن پول',
  'Deleting or overwriting files': 'حذف یا بازنویسی فایل‌ها',
  'Sharing files outside': 'هم‌رسانی فایل با بیرون',
  'Signing up or changing accounts': 'ثبت‌نام یا تغییر حساب‌ها',
  'This is what would be sent': 'این همان چیزی است که فرستاده می‌شود',
  'This is what would be posted': 'این همان چیزی است که منتشر می‌شود',
  'This is what would be paid': 'این همان چیزی است که پرداخت می‌شود',
  'This is what would be deleted': 'این همان چیزی است که حذف می‌شود',
  'This is what would be shared': 'این همان چیزی است که هم‌رسانی می‌شود',
  'This is what would change': 'این همان چیزی است که تغییر می‌کند',
  'This is what would happen': 'این همان چیزی است که رخ می‌دهد',
  'Approve and send': 'تأیید و فرستادن',
  'Approve and post': 'تأیید و انتشار',
  'Approve and delete': 'تأیید و حذف',
  'Approve and share': 'تأیید و هم‌رسانی',
  'Approve the change': 'تأیید تغییر',
  'The message goes out at once and cannot be taken back.': 'پیام بی‌درنگ فرستاده می‌شود و برگرداندنی نیست.',
  'People see the post straight away. You can delete it later, but people may already have read it.': 'مردم پست را بی‌درنگ می‌بینند. بعداً می‌توانید حذفش کنید، اما ممکن است کسانی آن را خوانده باشند.',
  'Money leaves your account. A payment is hard to undo.': 'پول از حساب شما خارج می‌شود. برگرداندن پرداخت دشوار است.',
  'Deleted files may not come back.': 'فایل‌های حذف‌شده شاید برنگردند.',
  'Whoever gets the files can keep them.': 'هر کس فایل‌ها را بگیرد می‌تواند نگهشان دارد.',
  'It changes an account in your name.': 'حسابی را به نام شما تغییر می‌دهد.',
  'It reaches something outside this computer.': 'به چیزی بیرون از این رایانه می‌رسد.',
  'Nothing is sent. {name} is told and can change it, or wait.': 'چیزی فرستاده نمی‌شود. به {name} خبر داده می‌شود و می‌تواند آن را تغییر دهد یا صبر کند.',
  'Nothing is posted. {name} is told and can change the text, or wait for a new date.': 'چیزی منتشر نمی‌شود. به {name} خبر داده می‌شود و می‌تواند متن را تغییر دهد یا منتظر تاریخ تازه بماند.',
  'Nothing is paid. {name} is told.': 'چیزی پرداخت نمی‌شود. به {name} خبر داده می‌شود.',
  'Nothing is deleted. {name} is told and keeps the files.': 'چیزی حذف نمی‌شود. به {name} خبر داده می‌شود و فایل‌ها می‌مانند.',
  'Nothing is shared. {name} is told.': 'چیزی هم‌رسانی نمی‌شود. به {name} خبر داده می‌شود.',
  'Nothing changes. {name} is told.': 'چیزی تغییر نمی‌کند. به {name} خبر داده می‌شود.',
  'Nothing happens. {name} is told.': 'اتفاقی نمی‌افتد. به {name} خبر داده می‌شود.',
  'Send this message?': 'این پیام فرستاده شود؟',
  'Post this online?': 'این در وب منتشر شود؟',
  'Make this payment?': 'این پرداخت انجام شود؟',
  'Delete these files?': 'این فایل‌ها حذف شوند؟',
  'Share this outside?': 'این با بیرون هم‌رسانی شود؟',
  'Make this account change?': 'این تغییر حساب انجام شود؟',
  'Go ahead with this?': 'این کار انجام شود؟',
  'Add a team member: ': 'افزودن عضو تازه: ',
  ', to ': '، به ',
  'Who would join': 'چه کسی می‌پیوندد',
  'Their instructions, in full': 'دستورکار کاملش',
  'Your assistant thinks a role is missing.': 'دستیار شما فکر می‌کند جای یک نقش خالی است.',
  'No one is added. Your assistant is told.': 'کسی افزوده نمی‌شود. به دستیار شما خبر داده می‌شود.',
  'Your team waits for your pick before it goes on.': 'تیم شما پیش از ادامه منتظر انتخاب شماست.',
  'You can close it without an answer. Your assistant is told and decides itself, or asks again.': 'می‌توانید بدون پاسخ ببندیدش. به دستیار شما خبر داده می‌شود و خودش تصمیم می‌گیرد یا دوباره می‌پرسد.',
  'Your assistant waits for your answer before it goes on.': 'دستیار شما پیش از ادامه منتظر پاسخ شماست.',
  'Nothing happens. Your assistant is told.': 'اتفاقی نمی‌افتد. به دستیار شما خبر داده می‌شود.',
  'Why it matters': 'چرا مهم است',
  'If you say no': 'اگر نه بگویید',
  'Ask ': 'از ',
  ' to change something': ' بخواهید چیزی را تغییر دهد',
  'What should change?': 'چه چیزی باید تغییر کند؟',
  'An answer here reaches your assistant the next time it checks.': 'پاسخ اینجا دفعه‌ی بعد که دستیار شما سر بزند به او می‌رسد.',
  'Free': 'آزاد',
  'Finished today': 'امروز تمام کرد',
  'The office room': 'اتاق دفتر',
  'Your campus': 'پردیس شما',
  ': not set up': ': هنوز راه نیفتاده',
  'Add an office': 'افزودن دفتر',
  'In this office': 'در این دفتر',
  'No one works here yet.': 'هنوز کسی اینجا کار نمی‌کند.',
  'New desk': 'میز تازه',
  'New desk in ': 'میز تازه در ',
  'is working on: ': 'در حال کار روی: ',
  'is working': 'در حال کار است',
  'Everyone is free right now.': 'الان همه آزادند.',
  'Reports to ': 'گزارش به ',
  'Answer': 'پاسخ',
  'Right now': 'همین حالا',
  'not counted': 'شمرده نمی‌شود',
  'job finished': 'کار تمام‌شده',
  'jobs finished': 'کار تمام‌شده',
  'Cost: ': 'هزینه: ',
  'Role file: ': 'فایل نقش: ',
  'Strength: ': 'توان: ',
  'Good at': 'کارهایی که خوب انجام می‌دهد',
  'What they do': 'چه کار می‌کند',
  'Asks you first before': 'پیش از این کارها از شما می‌پرسد',
  'Nothing: every action is allowed or never done.': 'هیچ: هر کار یا آزاد است یا هرگز انجام نمی‌شود.',
  'Never does: ': 'هرگز انجام نمی‌دهد: ',
  'Recent jobs': 'کارهای اخیر',
  'No jobs yet.': 'هنوز کاری نکرده است.',
  'Safety rules for this member': 'قاعده‌های ایمنی این عضو',
  'Instructions and earlier versions': 'دستورکار و نسخه‌های پیشین',
  'Give ': 'به ',
  ' a task': ' یک کار بدهید',
  'Always ask me': 'همیشه از من بپرس',
  'Careful': 'با احتیاط',
  'Leaves': 'بیرون می‌رود',
  'Computer only': 'فقط از رایانه',
  'From my phone too': 'از گوشی هم',
  'Arsenale asks and records. It cannot stop another program from acting, so keep sensitive accounts signed out of your assistant.': 'Arsenale می‌پرسد و ثبت می‌کند. نمی‌تواند جلوی کار برنامه‌ای دیگر را بگیرد، پس حساب‌های حساس را در دستیارتان باز نگذارید.',
  'Newsletter writer': 'نویسنده‌ی خبرنامه',
  'Reply drafter': 'پیش‌نویس‌کننده‌ی پاسخ',
  'Note taker': 'یادداشت‌بردار',
  'Newsletters,Short summaries': 'خبرنامه,خلاصه‌های کوتاه',
  'Friendly replies,Customer questions': 'پاسخ‌های دوستانه,پرسش‌های مشتری',
  'Minutes,To-do lists': 'صورت‌جلسه,فهرست کارها',
  'they': 'او',
  'Describe the job in plain words': 'کار را به زبان ساده بگویید',
  'Write my own': 'خودم می‌نویسم',
  'e.g. Ada': 'مثلاً آدا',
  'e.g. Press release writer': 'مثلاً نویسنده‌ی خبر مطبوعاتی',
  'Please give a job title so the team list is easy to read.': 'لطفاً عنوان شغلی بدهید تا فهرست تیم خوانا باشد.',
  'What should ': '',
  ' do?': ' چه کاری انجام دهد؟',
  'Describe the job in a few more words (at least 10 characters).': 'کار را با چند کلمه‌ی بیشتر بگویید (دست‌کم ۱۰ نویسه).',
  '+ Add': '+ افزودن',
  'Pick a look': 'یک چهره انتخاب کنید',
  'Look ': 'چهره‌ی ',
  'never': 'هرگز',
  'Unticked: allowed without asking. Paying always asks.': 'بدون تیک: بی‌پرسش آزاد است. پرداخت همیشه پرسیده می‌شود.',
  'More options': 'گزینه‌های بیشتر',
  'In one line, for the team list': 'در یک خط، برای فهرست تیم',
  'Left empty, the first sentence of the job is used.': 'اگر خالی بماند، نخستین جمله‌ی شرح کار به کار می‌رود.',
  'Add to ': 'افزودن به ',
  'Next: check the file': 'بعدی: بررسی فایل',
  'Edit ': 'ویرایش ',
  'Spreadsheets': 'جدول‌ها',
  'Everything your team has made for you, newest first.': 'هر چه تیم شما برایتان ساخته است، تازه‌ترین بالا.',
  'Search by name or person': 'جست‌وجو با نام یا شخص',
  'What your team hands in appears here: documents, pictures, tables and links.': 'آنچه تیم شما تحویل می‌دهد اینجا می‌آید: سند، تصویر، جدول و پیوند.',
  'new': 'تازه',
  'Nothing matches.': 'چیزی پیدا نشد.',
  'Open page': 'باز کردن صفحه',
  'Preview': 'پیش‌نمایش',
  'Preview: ': 'پیش‌نمایش: ',
  'Arsenale keeps its own copies: ': 'Arsenale نسخه‌های خودش را نگه می‌دارد: ',
  'Open in a new tab': 'باز کردن در زبانه‌ی تازه',
  'For the task: ': 'برای کار: ',
  'open it': 'باز کردن',
  'Assistants': 'دستیارها',
  'Phone alerts': 'هشدار روی گوشی',
  'Safety rules': 'قاعده‌های ایمنی',
  'Your assistants': 'دستیارهای شما',
  'The AI chats that do the work': 'گفت‌وگوهای هوش مصنوعی که کار را انجام می‌دهند',
  'Connected, last heard ': 'وصل است، آخرین تماس ',
  'Connected': 'وصل است',
  'Not available': 'در دسترس نیست',
  'Connect': 'وصل کردن',
  'What Arsenale remembers': 'آنچه Arsenale به یاد دارد',
  'Advanced: custom instructions and MCP over HTTP': 'پیشرفته: دستورهای سفارشی و MCP روی HTTP',
  'MCP over HTTP': 'MCP روی HTTP',
  'Add Arsenale to ': 'افزودن Arsenale به ',
  'Added': 'افزوده شد',
  'One new entry in the settings file of ': 'یک ورودی تازه در فایل تنظیمات ',
  '. A backup is kept next to it.': '؛ یک نسخه‌ی پشتیبان کنارش نگه داشته می‌شود.',
  'Run this command once in a terminal.': 'این دستور را یک بار در پایانه اجرا کنید.',
  'Open the link; your editor asks you to confirm.': 'پیوند را باز کنید؛ ویرایشگرتان از شما تأیید می‌خواهد.',
  'Let Arsenale add itself': 'بگذارید Arsenale خودش را اضافه کند',
  'Restart ': 'باز کردن دوباره‌ی ',
  'Close it fully and open it again.': 'آن را کامل ببندید و دوباره باز کنید.',
  'Say hello': 'سلام کنید',
  'Type this in a new chat:': 'این را در یک گفت‌وگوی تازه بنویسید:',
  'Say hello to Arsenale': 'به Arsenale سلام کن',
  'Connected. Arsenale heard from ': 'وصل شد. Arsenale صدای این دستیار را شنید: ',
  'Not yet. Check the steps, then press Test.': 'هنوز نه. گام‌ها را بررسی کنید و بعد «آزمایش» را بزنید.',
  'Waiting to hear from ': 'در انتظار شنیدن از ',
  'Every job it does now shows up here.': 'از این پس هر کاری بکند اینجا دیده می‌شود.',
  'Turns green when it answers.': 'وقتی پاسخ دهد سبز می‌شود.',
  'Restart your assistant, then say hello.': 'دستیارتان را دوباره باز کنید و بعد سلام کنید.',
  'While this page is open in a tab': 'تا وقتی این صفحه در یک زبانه باز است',
  'When your assistant asks you something, when a task waits for you, or when a budget alert comes in.': 'وقتی دستیارتان چیزی می‌پرسد، کاری منتظر شماست، یا هشدار بودجه‌ای می‌رسد.',
  'Get a buzz when your team needs you': 'وقتی تیم به شما نیاز دارد خبردار شوید',
  'Send alerts to my phone': 'هشدارها را به گوشی‌ام بفرست',
  'Using the free ntfy app. No account with Arsenale.': 'با برنامه‌ی رایگان ntfy. بدون حساب در Arsenale.',
  'Through a Telegram bot you create.': 'از راه یک ربات تلگرام که خودتان می‌سازید.',
  'Through the Pushover app. It only notifies: no buttons.': 'از راه برنامه‌ی Pushover. فقط خبر می‌دهد: دکمه ندارد.',
  'Send a test first.': 'اول یک آزمایش بفرستید.',
  'Show the question, with Approve and Decline': 'پرسش را با دکمه‌های تأیید و رد نشان بده',
  'Paired with ': 'جفت‌شده با ',
  'one private chat': 'یک گفت‌وگوی خصوصی',
  'Open this link on your phone within 10 minutes, and press Start in Telegram:': 'این پیوند را تا ۱۰ دقیقه‌ی دیگر روی گوشی باز کنید و در تلگرام «Start» را بزنید:',
  'Pair your phone: Arsenale makes a one-time link for your bot.': 'گوشی‌تان را جفت کنید: Arsenale برای ربات شما یک پیوند یک‌بارمصرف می‌سازد.',
  'Pair another phone': 'جفت کردن گوشی دیگر',
  'Pair a phone': 'جفت کردن گوشی',
  'Send a test alert': 'فرستادن هشدار آزمایشی',
  'Last test: ': 'آخرین آزمایش: ',
  'What your phone shows': 'آنچه گوشی شما نشان می‌دهد',
  ' asks: ': ' می‌پرسد: ',
  'Tap to Approve or Decline.': 'برای تأیید یا رد ضربه بزنید.',
  'Open Arsenale to answer: payments, hires and plain approvals are never answered from a phone.': 'برای پاسخ Arsenale را باز کنید: پرداخت، استخدام و تأییدهای ساده هرگز از گوشی پاسخ داده نمی‌شوند.',
  'Open Arsenale to answer.': 'برای پاسخ Arsenale را باز کنید.',
  'What your team must ask you before doing': 'آنچه تیم شما پیش از انجام باید از شما بپرسد',
  'Ready-made teams': 'تیم‌های آماده',
  'Installing one adds the office and its team members; removing it keeps every file you changed and all history.': 'نصب یکی، دفتر و اعضای تیمش را اضافه می‌کند؛ حذفش هر فایلی را که تغییر داده‌اید و همه‌ی سابقه را نگه می‌دارد.',
  'members': 'عضو',
  'Add': 'افزودن',
  'version ': 'نسخه‌ی ',
  'Add this office': 'افزودن این دفتر',
  'This page opens only with your own key, kept in a file only your account can read. Another account on this computer cannot open it.': 'این صفحه فقط با کلید خود شما باز می‌شود که در فایلی نگه داشته شده که فقط حساب شما می‌تواند بخواند. حساب دیگری روی این رایانه نمی‌تواند بازش کند.',
  'SETUP': 'راه‌اندازی',
  'Welcome': 'خوش آمدید',
  'Step ': 'گام ',
  ' of 4': ' از ۴',
  'Welcome. Let us build your office.': 'خوش آمدید. بیایید دفترتان را بسازیم.',
  'You give jobs in plain words. Your team gets them done and asks you before anything leaves this computer.': 'شما کار را به زبان ساده می‌سپارید. تیم شما انجامش می‌دهد و پیش از آنکه چیزی از این رایانه بیرون برود از شما می‌پرسد.',
  'What is your company called?': 'نام شرکت شما چیست؟',
  'What does it do?': 'چه کار می‌کند؟',
  'Helps your team write in the right tone.': 'به تیم شما کمک می‌کند با لحن درست بنویسد.',
  'On a plan Arsenale shows time, not money. Budgets can be set later.': 'با اشتراک ماهانه، Arsenale زمان را نشان می‌دهد نه پول. بودجه را بعداً هم می‌شود گذاشت.',
  'Nothing is saved until the last step. About 3 minutes.': 'تا گام آخر چیزی ذخیره نمی‌شود. حدود ۳ دقیقه.',
  'Choose offices': 'انتخاب دفترها',
  'Which offices do you need?': 'به کدام دفترها نیاز دارید؟',
  'You can add or remove offices later in Settings.': 'بعداً در تنظیمات می‌توانید دفتر اضافه یا حذف کنید.',
  'Campaigns, copy, social posts, newsletters': 'کمپین، متن تبلیغاتی، پست شبکه‌های اجتماعی، خبرنامه',
  'Replies, tickets, help pages': 'پاسخ‌ها، درخواست‌ها، صفحه‌های راهنما',
  'Invoices, expenses, budget in plain words': 'صورت‌حساب، هزینه‌ها، بودجه به زبان ساده',
  'Job ads, interviews, first-week plans': 'آگهی شغلی، مصاحبه، برنامه‌ی هفته‌ی اول',
  'Agendas, minutes, supplier requests': 'دستور جلسه، صورت‌جلسه، درخواست از تأمین‌کننده',
  'Sources, competitors, fact-checks': 'منابع، رقیبان، راستی‌آزمایی',
  'Moodboards, palettes, layout briefs': 'مودبورد، پالت رنگ، شرح صفحه‌آرایی',
  'office': 'دفتر',
  'offices': 'دفتر',
  'Connect assistant': 'وصل کردن دستیار',
  'ChatGPT: not yet': 'ChatGPT: هنوز نه',
  'Ready to open the doors?': 'آماده‌اید درها را باز کنید؟',
  'Nothing has been saved yet. Check the summary.': 'هنوز چیزی ذخیره نشده است. خلاصه را بررسی کنید.',
  'Company': 'شرکت',
  'Assistant': 'دستیار',
  'Safe by default.': 'از پیش ایمن.',
  'Your team asks you first before it sends, posts, pays or deletes anything.': 'تیم شما پیش از فرستادن، انتشار، پرداخت یا حذف هر چیزی اول از شما می‌پرسد.',
  'Arsenale will create these files and folders, and nothing else': 'Arsenale این فایل‌ها و پوشه‌ها را می‌سازد و هیچ چیز دیگری را',
  'Create my team': 'ساختن تیمم',
  'Your company is set up': 'شرکت شما راه افتاد',
  'Give your first task, and your assistant sees it the next time you talk to it.': 'نخستین کارتان را بسپارید؛ دستیار شما دفعه‌ی بعد که با او حرف بزنید آن را می‌بیند.',
  'Open my campus': 'باز کردن پردیسم',
  'Hello! I am your assistant. Tell me about your company and we will build your team together.': 'سلام! من دستیار شما هستم. از شرکتتان بگویید تا با هم تیمتان را بسازیم.',
  'Tick an office and its building appears on your campus.': 'دفتری را تیک بزنید تا ساختمانش در پردیس شما پیدا شود.',
  'Almost there. I will wait right here until I hear from you.': 'تقریباً رسیدیم. همین‌جا منتظر می‌مانم تا از شما بشنوم.',
  'This is your campus. Everyone is ready at their desk.': 'این پردیس شماست. همه پشت میزشان آماده‌اند.',
  'Your company is set up. Give me a first task whenever you like.': 'شرکت شما راه افتاد. هر وقت خواستید نخستین کار را به من بسپارید.',
  'connected': 'وصل شد',
  'waiting…': 'در انتظار…',
  'Your AI team: ': 'تیم هوش مصنوعی شما: ',
  'They ask you first before anything leaves the computer.': 'پیش از آنکه چیزی از رایانه بیرون برود از شما می‌پرسند.',
  'Owner. Gives tasks and says yes or no.': 'مالک. کار می‌سپارد و بله یا نه می‌گوید.',
  'gives tasks, answers questions': 'کار می‌سپارد، به پرسش‌ها پاسخ می‌دهد',
  'Takes on each role.': 'هر نقشی را بر عهده می‌گیرد.',
  'active, last seen ': 'فعال، آخرین بار ',
  'hands each job to a team member': 'هر کار را به یک عضو تیم می‌سپارد',
  'Ready to add': 'آماده‌ی افزودن',
  'Office packs in Settings': 'بسته‌های دفتر در تنظیمات',
  'Arsenale shows you each change before it makes it, and keeps a backup.': 'Arsenale هر تغییری را پیش از انجام به شما نشان می‌دهد و یک نسخه‌ی پشتیبان نگه می‌دارد.',
  'Finished': 'تمام شد',
  'Cannot connect yet.': 'هنوز وصل‌شدنی نیست.',
  'Within 10 minutes, send this to your bot in a private chat:': 'تا ۱۰ دقیقه‌ی دیگر این را در یک گفت‌وگوی خصوصی برای ربات خود بفرستید:',
  // ---------- security fixes
  'a hard link to another file': 'پیوند سخت به فایلی دیگر',
  'The deliverable store is full (5 GB): nothing more is stored': 'انبار تحویلی‌ها پر است (۵ گیگابایت): چیز دیگری نگه داشته نمی‌شود',
  'This page lost its key. Open the dashboard again with arsenale open.': 'این صفحه کلیدش را از دست داده است. داشبورد را دوباره با arsenale open باز کنید.',
  'This dashboard opens only with its key. Run `arsenale open`, or open the address that `arsenale serve` printed.': 'این داشبورد فقط با کلید خودش باز می‌شود. دستور `arsenale open` را اجرا کنید، یا نشانی‌ای را که `arsenale serve` چاپ کرد باز کنید.',
}

/** English is the source text; a missing fa key falls back to it. */
function t(lang, key) {
  if (lang === 'fa' && Object.prototype.hasOwnProperty.call(FA, key)) return FA[key]
  return key
}

/** The EN | FA switch in the header, shared by the office and archive shells.
 *  The Persian side is spelled "FA" on the English page, so an English page has
 *  no Arabic script at all; the Persian page spells it "فا". */
function langSwitch(lang) {
  return '<div class="langsw" role="group" aria-label="' + t(lang, 'Language') + '">'
    + '<button type="button" data-lang="en" aria-pressed="' + (lang !== 'fa') + '">EN</button>'
    + '<button type="button" data-lang="fa" aria-pressed="' + (lang === 'fa') + '">' + (lang === 'fa' ? 'فا' : 'FA') + '</button></div>'
}

/** The language is remembered in one place the server can read: the
 *  `dash-lang` cookie. The server picks the language per request, in this
 *  order: ?lang= in the address, then the cookie, then English. So a page
 *  opened with a bare address (bookmark, the Archive link, a reload) already
 *  arrives in the chosen language, with no redirect and no flash of the other
 *  one. localStorage is only a fallback for a browser that refuses cookies. */
function langFromRequest(query, cookieHeader) {
  const ok = (v) => (v === 'fa' || v === 'en' ? v : '')
  const fromQuery = ok(new URLSearchParams(query || '').get('lang'))
  const m = /(?:^|;\s*)dash-lang=(\w+)/.exec(cookieHeader || '')
  return { lang: fromQuery || ok(m && m[1]) || 'en', explicit: !!fromQuery }
}

/** The client-side half of the switch: FA/LANG/T so officeClient, controlRoom
 *  and the archive's SCRIPT can call T(key) themselves, plus what makes a
 *  language choice stick. A click on EN/FA stores the choice and loads the
 *  page again in that language (the shell text is rendered on the server);
 *  an explicit ?lang= in the address is stored too and then removed from the
 *  address, so an old address in another tab cannot undo a later choice.
 *  The built file (not live) has no switch: it cannot be re-rendered. */
function langScript(lang, live) {
  return 'const FA = ' + JSON.stringify(FA) + ';\n'
    + 'const LANG = ' + JSON.stringify(lang) + ';\n'
    + "function T(key) { return LANG === 'fa' && Object.prototype.hasOwnProperty.call(FA, key) ? FA[key] : key }\n"
    + (live ? '(function () {\n'
      + "  function save(l) { try { localStorage.setItem('dash-lang', l) } catch (e) {} document.cookie = 'dash-lang=' + l + '; path=/; max-age=31536000; SameSite=Strict' }\n"
      + "  var u = new URL(location.href), q = u.searchParams.get('lang')\n"
      + "  if (q === 'en' || q === 'fa') { save(q); u.searchParams.delete('lang'); try { history.replaceState(null, '', u.pathname + u.search + u.hash) } catch (e) {} }\n"
      + '  else {\n'
      // cookie refused or cleared: fall back to what this browser stored
      + "    try { var s = localStorage.getItem('dash-lang'); if ((s === 'en' || s === 'fa') && s !== LANG) { u.searchParams.set('lang', s); location.replace(u) } } catch (e) {}\n"
      + '  }\n'
      // another open tab changed the language: this one follows (after a reload, so the shell text changes too)
      + "  window.addEventListener('storage', function (e) { if (e.key === 'dash-lang' && (e.newValue === 'en' || e.newValue === 'fa') && e.newValue !== LANG) location.reload() })\n"
      + "  document.addEventListener('click', function (e) {\n"
      + "    var b = e.target.closest('[data-lang]'); if (!b) return\n"
      + '    var l = b.dataset.lang\n'
      + '    if (l === LANG) return\n'
      + '    save(l)\n'
      + "    var n = new URL(location.href); n.searchParams.set('lang', l); location.href = n.toString()\n"
      + '  })\n'
      + '})();' : '')
}

module.exports = { FA, t, langSwitch, langScript, langFromRequest }
